### ISSUE TITLE
Lỗi - Menu Viện Phí - 1 số chức năng BC bị lỗi

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#1]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **18/08/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_timmach_ct_t5`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [``](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_bo_sung](https://img.shields.io/badge/Menu%20Viện%20Phí-:-blue?style=plastic&logo=github)
   > _**Thangkt**_: `05`_**Namkt**_: `2022`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Menu viện phí: 1 số chức năng trong menu khi vào xem bị lỗi!
 + Bảng kê thu chi.
 + VP theo dịch vụ - Tổng hợp.
 + VP theo dịch vụ - Chi thiết
 + Biên lai: 1 số chức năng không chạy được.
     - Bảng kê biên lai thu.
     - Bảng kê quyển biên lai.
  + Theo dõi tạm ứng nội trú -> không load được dữ liệu.

```
Một số hình ảnh lỗi!
+ Bảng kê thu chi.
![image](https://user-images.githubusercontent.com/96155021/185333802-28828cd8-8f12-44d9-abe9-6045a126a803.png)

 + VP theo dịch vụ - Tổng hợp.
![image](https://user-images.githubusercontent.com/96155021/185333958-5adb9803-5dc4-4197-8bef-f3f5cfd09acd.png)
  + Theo dõi tạm ứng nội trú -> không load được dữ liệu.
report
![image](https://user-images.githubusercontent.com/96155021/185334014-ad12a452-a67a-4f08-be2e-773a341e923c.png)
Fees
![image](https://user-images.githubusercontent.com/96155021/185334146-e8cd138e-3e7a-4bfe-9107-c550f72599fa.png)

**Comment by nvvinh-dh** [comment]
![image](https://user-images.githubusercontent.com/97591404/185522683-e7a8ae8c-ff4e-4140-a3a3-1d82496fc93d.png)

@le-an-87 các lỗi ở trên em nhờ @ongtrieuhau kiểm tra dùm anh. Cụ thể các bảng kê ở trên Reports sử dụng từ HosFees.dll phiên bản 3.22.720.3 (như hình ở trên).

Trong đó:
- Bảng kê thu chi: `objFrmBKThuChi = new HosFees.ReportsV2.ReportForms.FrmBKThuChi(ClsInfo.strNamKT, ClsInfo.strThangKT, ClsInfo.ngaylamviec, HosFees.DataAccessV2.RptCondition.v_NoiTru.TatCa);`
- VP theo dịch vụ - Tổng hợp: `HosFees.Classes.ShowForm.TongHopDV(ClsInfo.strUserName, ClsInfo.strNamKT, ClsInfo.strThangKT, ClsInfo.ngaylamviec, OTH.Entity.Enum.Hos.v_LoaiKCB.TatCa, OTH.Entity.Enum.HosFees.Reports.TongHopDV.v_LoaiTongHop.TongHopDV, this);`
- Theo dõi tạm ứng nội trú: `HosFees.Classes.ShowForm.TongHopDV(ClsInfo.strUserName, ClsInfo.strNamKT, ClsInfo.strThangKT, ClsInfo.ngaylamviec, OTH.Entity.Enum.Hos.v_LoaiKCB.TatCa, OTH.Entity.Enum.HosFees.Reports.TongHopDV.v_LoaiTongHop.ChiTietDV, this);`

**Comment by nghivanbi** [comment]
![image](https://user-images.githubusercontent.com/91751241/185528321-e45086a9-8a2e-40c7-b45b-d9451287933f.png)
add lại dll này xem Vinh

**Comment by nvvinh-dh** [comment]
Cũng y chang, không thay đổi!

**Comment by nghivanbi** [comment]
Cho link report mới nhất cái.

**Comment by le-an-87** [comment]
alo anh @nvvinh-dh ơi!
coi bỏ cái tab này luôn đi anh!
![image](https://user-images.githubusercontent.com/96155021/185559365-b225f52b-40ca-471b-8ce6-68deb33246ae.png)

**Comment by le-an-87** [comment]
Chức năng kiểm tra thông tuyến trong form xuất XML cũng mất nữa anh @nvvinh-dh ơi!
anh xem bổ sung chổ đó lại được không anh
![image](https://user-images.githubusercontent.com/96155021/185561613-1a61b328-0400-42f2-8d9b-3b4b50e00671.png)

**Comment by nvvinh-dh** [comment]
- @le-an-87 cái form "Tổng hợp biên lai thu viện phí" anh đang sử dụng hàm: `FrmQuyenHD = new HosFees.ReportsV2.ReportForms.FrmQuyenHD(ClsInfo.strNamKT, ClsInfo.strThangKT, ClsInfo.ngaylamviec);`. Còn tại sao nó khác với cái form ở Fees nhờ @ongtrieuhau giải thích dùm nhe!
- Form theo dõi tạm ứng anh trao đổi với @vuongdh rồi. @vuongdh xác nhận chức năng đó không xem được tất cả các khoa. Chỉ xem được từng khoa.
- Chức năng thông tuyến bị lỗi lâu rồi, anh đã báo @nghivanbi nhưng tới nay vẫn chưa có DLL cập nhật. Em cần thì tạm thời anh mở lại để em test.

**Comment by le-an-87** [comment]
chổ theo dõi tạm ứng không xem được tất cả thì anh chỉnh chổ đó lại bỏ xem tất cả đi anh @vuongdh ơi!
Chổ kiểm tra thông tuyến anh @nvvinh-dh mở lại đi! nếu lỗi gì thì em test rồi chụp hình lên đây fix luôn!

**Comment by le-an-87** [comment]
Chổ kiểm tra thông tuyến chưa mở lại!
