### ISSUE TITLE
Lỗi - xuất xml 4210 báo lỗi

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#10]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **03/10/2020**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_nhonai_20221003`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022000287` - _**MaKB**_: `2210000001` - _**NgayKCB**_: `03/10/2022` - _**MaPhong**_: `01` - _**MaDV**_: `01` - _**ThangKT**_: `10` - _**NamKT**_: `2022`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Xuất dữ liệu XML 4210 báo lỗi!
tất cả bệnh nhân đều lỗi.

```
![image](https://user-images.githubusercontent.com/96155021/193514796-9731a0e1-83d5-4413-acf1-e354bdf73ef5.png)

**Comment by vinh-dh** [comment]
Cái này không phải lỗi nhe. Nguyên nhân là data cấu trúc bị thiếu cột mamay table psmotaxn.

**Comment by le-an-87** [comment]
cái này phải cập nhật cấu trúc hay sao anh!
cấu trúc ở admin đã cập nhật hết rồi anh ơi!

**Comment by vinh-dh** [comment]
Nếu cấu trúc đã mất thì em tạo lại cho nó đi. Còn tại sao nó mất thì cái này anh không rõ rồi.
