### ISSUE TITLE
Lỗi - Ten_benh xml 1 đối với bệnh án ngoại trú thanh toán theo đợt không lấy theo lần khám cuối theo yêu cầu của PK Medic miền đông 74206

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#100]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **26/12/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `74206`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PK Medic miền đông**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_medic_bant_25122023`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_medic_bant_25122023`](https://gofile.me/78TQg/j0PBJSlIx)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2019003789` - _**MaKB**_: `2312010696` - _**MaBA**_: `N2023017900` _**NgayKCB**_: `23/12/2023` - _**MaPhong**_: `02` - _**MaDV**_: `10` - _**ThangKT**_: `12` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Phòng khám Medic miền đông đã yêu cầu tên bệnh xml 1 đối với bệnh án ngoại trú theo đợt chỉ lấy theo lần khám cuối.
Hiện tại Reports phiên bản ngày 22/12/2023 gôm hết chẩn đoán theo đợt điều trị của bệnh nhân.
Phiên bản Reports ngày 19/12/2023 còn lấy theo chẩn đoán cuối.
```
Tên bệnh ở 2 phiên bản khác nhau
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/da36212f-1890-42af-aa8d-7ab60a4b8aed)

**Comment by vinh-dh** [comment]
[Lỗi - TEN_BENH XML1 không lấy được tên bệnh YHCT #98](https://github.com/dh-hos/dhg.hospitalreports/issues/98)

**Comment by le-an-87** [comment]
Chổ này có gải quyết cho PK không anh @vinh-dh ? để em trả lời với pk luôn

**Comment by vinh-dh** [comment]
Fix theo báo lỗi của Trà luôn rồi đó @le-an-87. Còn PK có y/c riêng thì lập y/c chờ duyệt anh làm theo y/c.

**Comment by le-an-87** [comment]
này lúc trước nó có yêu cầu và làm rồi mà anh. anh cập nhật bản mới bổ sung thêm yhct mới bị mà

**Comment by vinh-dh** [comment]
Như vậy PK hơi phi lý. Lúc trước y/c như vậy nhưng lại báo lỗi #98. Trong báo lỗi của PK thì @chauthanhtra dẫn chứng Reports làm sai so với mô tả thì anh fix lại theo mô tả. Giờ PK muốn cụ thể như thế nào thì y/c bổ sung đi.

**Comment by le-an-87** [comment]
ok anh!
