### ISSUE TITLE
XML5 CỘT PHAU_THUAT NỘI DUNG BỊ DOUBLE

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hospitalreports#101]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HÒA**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **02/01/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `82242`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BVĐK TÂM MINH ĐỨC TIỀN GIANG**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_tmd2023000204`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023005460` - _**MaKB**_: `MaKB` - _**MaBA**_: `2023000204` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `18` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

trường hợp 2 phẫu thuật khác nhau nhưng người dùng gõ trình tự phẫu thuật giống nhau xảy ra double chuỗi trên XML5

![image](https://github.com/dh-hos/dhg.hospitalreports/assets/130281806/b5cf2c04-af08-4540-98d8-d220585d1db0)
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/130281806/4f52a6aa-bebe-4f4b-9d2f-3c42cc4a56bf)
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/130281806/5ae53ca3-f806-4ee7-b21e-d5e5bd0f0518)
![z5023487740707_02eaba33a5485610d429e6237e0abe57](https://github.com/dh-hos/dhg.hospitalreports/assets/130281806/e88f4236-9c46-41bd-8c0a-7a8f2ac9339d)

**Comment by nqhoa1005** [comment]
anh @vinh-dh hỗ trợ dùm em do ngày 5/1 là hết hạn gửi hồ sơ của đơn vị, họ hối quá

**Comment by vinh-dh** [comment]
Hôm nay không kịp đâu.

**Comment by vinh-dh** [comment]
- File: [SetupHospitalReport20240110.zip](https://gofile.me/78TQg/9ZlS3PeMl) - [Nhật ký phiên bản](https://github.com/dh-hos/dhg.hospitalreports/blob/main/CHANGELOG.md)
