### ISSUE TITLE
Lỗi - Mẫu in C79a-DH theo 4210 không hiển thị năm sinh bệnh nhân Nữ

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalreports#102]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **4/1/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `51010`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Đặng Thùy Trâm**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_dangthuytram_mau794210_tuoinu`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/10wnhxAa1)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `4/1/2023` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `01` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

- Mẫu in tự thiết kế C79a-HD theo 4210 ngoại trú không hiển thị năm sinh bệnh nhân giới tính Nữ 
- Tên form in ghi sai thành Mau25aCT

![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/97272332/0da5a086-3dd7-40cd-bcec-49f1719a5420)

**Comment by vinh-dh** [comment]
2 phương án để fix lỗi này:
1) Cập nhật bản mới, load lại mẫu tự thiết kế:
- File: [SetupHospitalReport20240111.zip](https://gofile.me/78TQg/9ZlS3PeMl) - [![View](https://img.shields.io/badge/-Nh%E1%BA%ADt%20k%C3%BD%20phi%C3%AAn%20b%E1%BA%A3n-informational)](https://github.com/dh-hos/dhg.hospitalreports/blob/main/CHANGELOG.md#file-setuphospitalreport20240111zip---11012024)

2) Hoặc vào mẫu tự thiết kế, điều chỉnh lại công thức như hình:
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/112069710/cad6dfbb-30c9-4aba-a0f1-48584e8927e2)
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/112069710/91732571-fcaf-45cd-a11c-ef7771653a07)

**Comment by vinh-dh** [comment]
Còn trường hợp tên form thì @ongtrieuhau xem hỗ trợ như thế nào nhé!
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/112069710/fca1535c-99cf-4138-8124-c95e92ab037b)
