### ISSUE TITLE
Lỗi - XML lêch tổng chi so với các cột tiền BHTT + BNCCT + BNTT + NGUONKHAC (BV ô Môn)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#103]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **22/01/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92007`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Ô Môn**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_omon_loi_xml_22012024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_omon_loi_xml_22012024`](https://gofile.me/78TQg/fY93cQIAY)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2021004125` - _**MaKB**_: `2401017709` - _**MaBA**_: `N2021001635` _**NgayKCB**_: `17/01/2024` - _**MaPhong**_: `PL` - _**MaDV**_: `008` - _**ThangKT**_: `01` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `05` - _**MaHH**_: `A518` - _**SoHD**_: `008.00377/202401` - _**NgayHD**_: `17/01/2024` - _**ThangKT**_: `01` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
XML1 và XML2 bệnh nhân có sử dụng thuốc nguồn khác
tổng chi (thành tiền) lệch tiền so với các cột cộng lại
TONGCHI # BHTT + BNCCT + BNTT + NGUONKHAC

```
XML1
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/45eede45-f47c-42cf-99d6-83b3ef556229)
XML2
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/4d077877-024d-4dad-bdcf-947308570621)
hình ảnh bảng kê 6556
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/0f6d639a-9d29-423f-9e85-8afd36419644)
Thông tin thuốc
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/ef14b5b2-aeb6-4da1-9a61-aad0c7b162f4)

**Comment by vinh-dh** [comment]
Đây đâu phải là lỗi "XML lêch tổng chi so với các cột tiền BHTT + BNCCT + BNTT + NGUONKHAC" @le-an-87. Anh thấy cột tổng chi phí đang đúng, không có sai.

Đây là BN HIV, anh thấy cột t_nguonkhac = 0. Như vậy là lỗi thể hiện sai chi phí cột này với cột t_bnctt mới đúng.

**Comment by vinh-dh** [comment]
- File: [SetupHospitalReport20240131.zip](https://gofile.me/78TQg/9ZlS3PeMl) - [![View](https://img.shields.io/badge/-Nh%E1%BA%ADt%20k%C3%BD%20phi%C3%AAn%20b%E1%BA%A3n-informational)](https://github.com/dh-hos/dhg.hospitalreports/blob/main/CHANGELOG.md#file-setuphospitalreport20240131zip---31012024)

**Comment by le-an-87** [comment]
Đã fix!
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/27c2a912-0d20-4374-91e6-05d8e9c9c7b3)
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/ef3bcd05-4737-4288-88e2-a5b72c1f5347)
