### ISSUE TITLE
Lỗi - Thống kê bệnh nhân khi Click số lượng Chuyển viện, xuất viện, tử vong 

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalreports#104]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **22/01/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87115`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện Phổi Đồng Tháp**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_phoidt`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

Report phiên bản 3.24.01.12.0 
Nội trú-> Thống kê bệnh nhân-> Xem báo cáo và Click số lượng Chuyển viện, xuất viện, tử vong  xuất hiện hộp thoại lỗi như hình dưới
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/97272364/2c628b7b-a312-4979-82c3-2a27463c3de8)

Chi tiết lỗi:
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Statistics.Books.Forms.FrmSoChuyenVien.filter()
   at Statistics.Books.Forms.FrmSoChuyenVien.cboBenhAn_ValueChanged(Object sender, EventArgs e)
   at Janus.Windows.GridEX.EditControls.MultiColumnCombo.OnValueChanged(EventArgs e)
   at Janus.Windows.GridEX.EditControls.MultiColumnCombo.a(Object , Boolean )
   at Statistics.Books.Forms.FrmSoChuyenVien.loadLoaiBenhAn()
   at Statistics.Books.Forms.FrmSoChuyenVien.FrmSoChuyenVien_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Reports
    Assembly Version: 3.24.112.0
    Win32 Version: 3.24.0112.0
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Reports/Reports.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Statistics
    Assembly Version: 1.24.112.0
    Win32 Version: 1.24.0112.0
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Reports/Statistics.DLL
----------------------------------------
Utilities
    Assembly Version: 1.24.112.0
    Win32 Version: 1.24.0112
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Reports/Utilities.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
LibraryApp
    Assembly Version: 4.23.1127.1
    Win32 Version: 4.23.1127.1
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Reports/LibraryApp.DLL
----------------------------------------
DataHelper
    Assembly Version: 1.24.112.0
    Win32 Version: 1.24.0112.0
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Reports/DataHelper.DLL
----------------------------------------
DH.PublicCLS
    Assembly Version: 3.24.112.0
    Win32 Version: 3.24.0112.0
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Reports/DH.PublicCLS.DLL
----------------------------------------
Janus.Windows.CalendarCombo.v3
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.0.22
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Reports/Janus.Windows.CalendarCombo.v3.DLL
----------------------------------------
Janus.Windows.Common.v3
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.0.22
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Reports/Janus.Windows.Common.v3.DLL
----------------------------------------
License
    Assembly Version: 3.23.1231.1
    Win32 Version: 3.23.1231.1
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Reports/License.DLL
----------------------------------------
OTH
    Assembly Version: 1.23.1208.1
    Win32 Version: 1.23.1208.1
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Reports/OTH.DLL
----------------------------------------
OTH.Entity
    Assembly Version: 1.23.1209.1
    Win32 Version: 1.23.1209.1
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Reports/OTH.Entity.DLL
----------------------------------------
Npgsql
    Assembly Version: 2.2.3.0
    Win32 Version: 2.2.3
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Reports/Npgsql.DLL
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
OTH.Common
    Assembly Version: 1.23.1208.0
    Win32 Version: 1.23.1208.0
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Reports/OTH.Common.DLL
----------------------------------------
Mono.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Reports/Mono.Security.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
Janus.Windows.GridEX.v3
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.0.22
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Reports/Janus.Windows.GridEX.v3.DLL
----------------------------------------
Janus.Windows.UI.v3
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.0.22
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Reports/Janus.Windows.UI.v3.DLL
----------------------------------------
MessageBoxAdv
    Assembly Version: 4.22.615.3
    Win32 Version: 4.22.0615.3
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Reports/MessageBoxAdv.DLL
----------------------------------------
OTH.Adapter
    Assembly Version: 1.23.1231.1
    Win32 Version: 1.23.1231.1
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Reports/OTH.Adapter.DLL
----------------------------------------
OTH.SQL
    Assembly Version: 1.22.615.4
    Win32 Version: 1.22.0615.4
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Reports/OTH.SQL.DLL
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
DH.BLLCLS
    Assembly Version: 3.24.112.0
    Win32 Version: 3.24.0112.0
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Reports/DH.BLLCLS.DLL
----------------------------------------
DH.DALCLS
    Assembly Version: 3.24.112.0
    Win32 Version: 3.24.0112.0
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Reports/DH.DALCLS.DLL
----------------------------------------
Janus.Windows.ExplorerBar.v3
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.0.22
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Reports/Janus.Windows.ExplorerBar.v3.DLL
----------------------------------------
System.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
Ctrl
    Assembly Version: 3.22.615.5
    Win32 Version: 3.22.0615.5
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Reports/Ctrl.DLL
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
OTH.ChilkatRR
    Assembly Version: 1.22.615.3
    Win32 Version: 1.22.0615.3
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Reports/OTH.ChilkatRR.DLL
----------------------------------------
ChilkatDotNet4
    Assembly Version: 9.5.0.73
    Win32 Version: 9.5.0.73
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Reports/ChilkatDotNet4.DLL
----------------------------------------
DH.HospitalLib
    Assembly Version: 1.22.1005.0
    Win32 Version: 1.22.1005.0
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Reports/DH.HospitalLib.DLL
----------------------------------------
HosMed.Core
    Assembly Version: 3.22.506.1
    Win32 Version: 3.22.0506.1
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Reports/HosMed.Core.DLL
----------------------------------------
HosReg.Code
    Assembly Version: 3.23.1016.2
    Win32 Version: 3.23.1016.2
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Reports/HosReg.Code.DLL
----------------------------------------
HosFees
    Assembly Version: 3.23.1221.7
    Win32 Version: 3.23.1221.7
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Reports/HosFees.DLL
----------------------------------------
HosFees.DataAccessV2
    Assembly Version: 3.23.1217.1
    Win32 Version: 3.23.1217.1
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Reports/HosFees.DataAccessV2.DLL
----------------------------------------
Statistics.Books
    Assembly Version: 1.24.112.0
    Win32 Version: 1.24.0112.0
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Reports/Statistics.Books.DLL
----------------------------------------
HosMed.BCDuoc
    Assembly Version: 3.21.302.0
    Win32 Version: 3.21.0302.0
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Reports/HosMed.BCDuoc.DLL
----------------------------------------
Statistics.HealthInsurance
    Assembly Version: 1.24.112.0
    Win32 Version: 1.24.0112.0
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Reports/Statistics.HealthInsurance.DLL
----------------------------------------
Utilities.Configuration
    Assembly Version: 1.24.112.0
    Win32 Version: 1.24.0112.0
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Reports/Utilities.Configuration.DLL
----------------------------------------
DH.BaoCao
    Assembly Version: 4.22.1006.2
    Win32 Version: 4.22.1006.2
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Reports/DH.BaoCao.DLL
----------------------------------------
DevExpress.Utils.v17.1
    Assembly Version: 17.1.3.0
    Win32 Version: 17.1.3.0
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Reports/DevExpress.Utils.v17.1.DLL
----------------------------------------
DH.ReportCLS
    Assembly Version: 3.24.112.0
    Win32 Version: 3.24.0112.0
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Reports/DH.ReportCLS.DLL
----------------------------------------
OTH.XForms
    Assembly Version: 1.23.1130.6
    Win32 Version: 1.23.1130.6
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Reports/OTH.XForms.DLL
----------------------------------------
ControlButton
    Assembly Version: 4.23.713.1
    Win32 Version: 4.23.0713.1
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Reports/ControlButton.DLL
----------------------------------------
Janus.Data.v3
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.0.22
    CodeBase: file:///C:/Program%20Files%20(x86)/DHG%20Pharma/DHG.Hospital%20Reports/Janus.Data.v3.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by vinh-dh** [comment]
- File: [SetupHospitalReport20240202.zip](https://gofile.me/78TQg/9ZlS3PeMl) - [![View](https://img.shields.io/badge/-Nh%E1%BA%ADt%20k%C3%BD%20phi%C3%AAn%20b%E1%BA%A3n-informational)](https://github.com/dh-hos/dhg.hospitalreports/blob/main/CHANGELOG.md#file-setuphospitalreport20240202zip---02022024)

**Comment by hvtuan1987** [comment]
ok rồi á anh !
