### ISSUE TITLE
Lỗi - XML1 BN Ngoại trú cột TEN_BENH bị Double chẩn đoán

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitalreports#109]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ĐỨC**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **14/03/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `74206`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Medic Miền Đông**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_medicmd_cdoan`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/K6xzjDtO7

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022076123` - _**MaKB**_: `2403000271` - _**MaBA**_: `MaBA` _**NgayKCB**_: `01/03/2024` - _**MaPhong**_: `11` - _**MaDV**_: `10` - _**ThangKT**_: `03` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```

```
Report XML1: BN Ngoại trú cột TEN_BENH bị Double chẩn đoán

Nội dung Cột ten_benh trên XML1= Nhục tý [**Đau cơ**];Dãn tĩnh mạch chi dưới;**Đau cơ**

theo [Mô tả](https://github.com/dh-hos/dhg.hospitalreports/files/13699096/Bi.-.Mo.ta.thuoc.ho.tro.benh.nhan.YHCT_20211201.2.pdf)  cột [TEN_BENH] = psdangky.kqcdoan = Nhục tý [**Đau cơ**];Dãn tĩnh mạch chi dưới;**Đau cơ**

![image](https://github.com/dh-hos/dhg.hospitalreports/assets/98437757/db7c7079-660f-46c3-bf9f-de23b37ffbee)

File XML 
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/98437757/897f8bc1-b1e4-40d9-afc5-5a05a86c6833)

**Comment by vinh-dh** [comment]
Đây là dữ liệu của `psdangky.kqcdoan`, như vậy đây không phải lỗi Reports nhé!
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/112069710/f6c27ad7-cac8-4096-830d-774d2c44c22f)
