### ISSUE TITLE
Yêu cầu - BV QDY ĐT: Mở lại chức năng kiểm tra thông tuyến trên bảng 1 XML của Reports

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalreports#11]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **03/10/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87044`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Quân Dân Y ĐT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_qdy_dt_bangketrungicdchinhphu`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

BV Quân Dân Y Đồng Tháp
Mở lại chứng năng kiểm tra thông tuyến trên bảng XML 1 module Reports 
![ảnh](https://user-images.githubusercontent.com/97272332/193530520-9a60bdc0-2b3e-48e6-b1cd-71f2e2260216.png)

**Comment by vinh-dh** [comment]
[Reports 04/10/2022](https://www.fshare.vn/file/TGFK9CP7KYU5)
