### ISSUE TITLE
Lỗi - Báo cáo mẫu 79 và 79 cv 4210 load thiếu bệnh nhân.

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#110]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **28/03/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_thotnot_toatt_27032024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_thotnot_toatt_27032024`](https://gofile.me/78TQg/o34bsM2J5)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**2024012043**_: `MaBN` - _**MaKB**_: `2403015711` - _**NgayKCB**_: `27/03/2024` - _**MaPhong**_: `20` - _**MaDV**_: `12` - _**ThangKT**_: `03` - _**NamKT**_: `2024`

   > _**2024012045**_: `MaBN` - _**MaKB**_: `2403015713` - _**NgayKCB**_: `28/03/2024` - _**MaPhong**_: `20` - _**MaDV**_: `12` - _**ThangKT**_: `03` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Các bệnh nhân chưa in bảng kê ở printer.

1. Báo cáo mẫu 79:
 - bệnh nhân 2024012045 khám có toa thuốc tủ trực và đã in bảng kê ở Prescription
 -> mẫu 79 chọn đã in hoặc chưa in đều không load được bệnh nhân này.
2. Báo cáo mẫu 79 cv 4210:
 - xuất báo cáo chọn Chưa in và tất cả đều không load được bệnh nhân.
```
1. mẫu 79
![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/f5002caa-8069-4d2d-adca-6807bbb34b51)
2. mẫu 79 cv 4210
![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/a8105235-fcef-4ce1-b520-86542a00307d)

**Comment by gh-dh-bot-00** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hospitalreports/110)

**Comment by vinh-dh** [comment]
Để a kiểm tra.

**Comment by vinh-dh** [comment]
- File: [SetupHospitalReport20240409.zip](https://gofile.me/78TQg/9ZlS3PeMl) - [![View](https://img.shields.io/badge/-Nh%E1%BA%ADt%20k%C3%BD%20phi%C3%AAn%20b%E1%BA%A3n-informational)](https://github.com/dh-hos/dhg.hospitalreports/blob/main/CHANGELOG.md#file-setuphospitalreport20240409zip---09042024)

**Comment by le-an-87** [comment]
alo anh @vinh-dh cho em hỏi trường hợp này
danh sách 
đã in = 0
chưa in = 5
tất cả = 7
lệch 2 bệnh
-> trường hợp này sao Reports không load lên vậy anh.
-> chổ mã bệnh khác có nhiều dấu ; đó anh
>![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/49a5e4fd-2e7a-4619-8119-51587da0b76c)

![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/e70ee915-3bfa-4aa1-a03a-873e90a2b897)

**Comment by vinh-dh** [comment]
- File: [SetupHospitalReport20240410.zip](https://gofile.me/78TQg/9ZlS3PeMl) - [![View](https://img.shields.io/badge/-Nh%E1%BA%ADt%20k%C3%BD%20phi%C3%AAn%20b%E1%BA%A3n-informational)](https://github.com/dh-hos/dhg.hospitalreports/blob/main/CHANGELOG.md#file-setuphospitalreport20240410zip---10042024)

**Comment by le-an-87** [comment]
Đã fix!
![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/d8c7096f-57a8-4522-b33d-ae9e1db4355e)
