### ISSUE TITLE
Lỗi - Không xem được danh sách khám sức khỏe đề án 06. (BV QDY ĐT)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#111]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **29/03/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_quandany_dt_loi_ksk`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_quandany_dt_loi_ksk`](https://gofile.me/78TQg/62qlV9uRD)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023029050` - _**MaKB**_: `2403017936` - _**NgayKCB**_: `28/03/2024` - _**MaPhong**_: `26` - _**MaDV**_: `10` - _**ThangKT**_: `03` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
bệnh nhân có đăng ký khám sức khỏe ngày 28/03/2024
- khi vào xem danh sách để cập nhật thông tin khám sức khỏe phần mềm báo lỗi.
- Khi nhập nơi cấp hơn 30 ký tự thực hiện lưu phần mềm báo lỗi.
-> đề nghị hiển thị thông báo khi nhập quá ký tự cho phép

```
![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/e9f51265-a316-4bc5-a2ae-93d4330ffa52)

![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/e1c3bafc-8b06-4c1b-96df-c466de4aa607)

**Comment by gh-dh-bot-01** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hospitalreports/111)

**Comment by vinh-dh** [comment]
@lequocthong29 em kiểm tra nhé!

**Comment by lequocthong29** [comment]
Update dll [DH.ThongTinKSK.dll](https://github.com/dh-hos/oLibraries/blob/main/DH.ThongTinKSK.dll)
- Fix lỗi phần mềm báo lỗi khi ấn nút xem, do load ca có nơi cấp lớn hơn 30 ký tự.
- Hiển thị thông báo khi nhập nơi cấp quá 30 ký tự.

@vinh-dh Build lại Reports dùm e nha a.

**Comment by vinh-dh** [comment]
- File: [SetupHospitalReport20240401.zip](https://gofile.me/78TQg/9ZlS3PeMl) - [![View](https://img.shields.io/badge/-Nh%E1%BA%ADt%20k%C3%BD%20phi%C3%AAn%20b%E1%BA%A3n-informational)](https://github.com/dh-hos/dhg.hospitalreports/blob/main/CHANGELOG.md#file-setuphospitalreport20240401zip---01042024)

**Comment by le-an-87** [comment]
Đã fix!
![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/d0900f61-3428-446c-8043-400083bfbc58)
![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/2ea8ba94-f757-4945-a5be-8d6751574f21)
