### ISSUE TITLE
Lỗi - Bệnh nhân chỉ định cận lâm sàng cho vật tư kèm theo nhưng không load mã vật tư và gói Vật tư XML3...

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalreports#112]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **01/04/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `89015`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh Viện Tim Mạch An Giang**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbtimmachangiang_vtkt`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024006338` - _**MaKB**_: `2403009235` - _**MaBA**_: `2024003719` _**NgayKCB**_: `18/03/2024 10:26:10 AM` - _**MaPhong**_: `E401` - _**MaDV**_: `06` - _**ThangKT**_: `03` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `03` - _**MaHH**_: `MSTT1103.64` - _**SoHD**_: `CT0.V24.0318.143254` - _**NgayHD**_: `18/03/2024` - _**ThangKT**_: `03` - _**NamKT**_: `2024`
  > _**KhoChan**_: `14` - _**KhoLe**_: `03` - _**MaHH**_: `MSTT1103.66` - _**SoHD**_: `CT0.V24.0318.143254` - _**NgayHD**_: `18/03/2024` - _**ThangKT**_: `03` - _**NamKT**_: `2024`
  > _**KhoChan**_: `14` - _**KhoLe**_: `03` - _**MaHH**_: `MSTT1103.52` - _**SoHD**_: `CT0.V24.0318.143254` - _**NgayHD**_: `18/03/2024` - _**ThangKT**_: `03` - _**NamKT**_: `2024`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `CH106` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`
Bệnh nhân có chỉ định cận lâm sàng: Chụp, nong động mạch vành bằng bóng (Mã cls CH106 ) có chỉ định vật tư kèm theo nhưng trên XLM 3 không thể hiện được Mã vật tư, Gói vật tư.. ngay tên cận lâm sàng như hình dưới
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/97272364/986a872d-1db3-4ee1-8651-d1ab15b69d9e)

Em có thử test bệnh nhân đó cho lại cls và vật tư kèm theo giống hệt zậy nhưng trên dữ liệu khác: tuan_dbtimmachag_vtkt
thì hiển thị được như hình dưới.
Nhờ anh coi dùm áh
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/97272364/d65f733a-d9f1-4630-a0ea-bf505cebb910)

**Comment by gh-dh-bot-00** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hospitalreports/112)

**Comment by vinh-dh** [comment]
Ok, để anh kiểm tra.

**Comment by vinh-dh** [comment]
- File: [SetupHospitalReport20240402.zip](https://gofile.me/78TQg/9ZlS3PeMl) - [![View](https://img.shields.io/badge/-Nh%E1%BA%ADt%20k%C3%BD%20phi%C3%AAn%20b%E1%BA%A3n-informational)](https://github.com/dh-hos/dhg.hospitalreports/blob/main/CHANGELOG.md#file-setuphospitalreport20240402zip---02042024)

**Comment by hvtuan1987** [comment]
ok rồi á anh !
