### ISSUE TITLE
Lỗi - In toa thuốc ngoại trú trên Reports

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalreports#114]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **11/4/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `84006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Trà Cú**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_tracu_dmcls_ptvocam_22032024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/OB0RiY2rg)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024005291` - _**MaKB**_: `2403009601` - _**MaBA**_: `MaBA` _**NgayKCB**_: `22/3/2024` - _**MaPhong**_: `07` - _**MaDV**_: `YHCT` - _**ThangKT**_: `03` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

In toa thuốc ngoại trú trên Reports bị lỗi

![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/97272332/ff30a9b0-5f66-419f-a114-20ab73051147)

**Comment by gh-dh-bot-00** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hospitalreports/114)

**Comment by nghivanbi** [comment]
XtraRPT kiểm tra DLL phiên bản mấy @vinh-dh ?

**Comment by vinh-dh** [comment]
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/112069710/cf88872a-f632-4cf3-aaf1-125f363b10db)

**Comment by nghivanbi** [comment]
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/91751241/af934f35-9e45-465d-83cc-78df3b43b522)

Cập nhật lại thử cái nhé.

**Comment by vinh-dh** [comment]
- File: [SetupHospitalReport20240411.zip](https://gofile.me/78TQg/9ZlS3PeMl)

**Comment by chauthanhtra** [comment]
- Phần mềm Reports mới đã fix được lỗi in toa thuốc ngoại trú

![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/97272332/1b482944-e3ea-49b5-bc76-4f6d1433e1b5)

- Test bệnh nhân mới chưa phát hiện lỗi in toa, các báo cáo, XML, bảng kê, thu phí bình thường

![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/97272332/dbf7773d-3411-4428-b23e-29a95e79144c)
![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/97272332/97c18847-aee1-4d29-aa05-4e41e691e5a0)
![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/97272332/ac9ab6d0-5d84-405f-99bc-d4c2df23878d)
![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/97272332/d5cefc87-c4ef-41ba-b785-6e57fe644324)
