### ISSUE TITLE
Lỗi - Xem Sổ nhập viện, Sổ xuất viện báo lỗi

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalreports#115]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **12/04/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `84006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Trà Cú**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_tracu_viettinbank_012024_10012024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/Cf33Tmhzm)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `01` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Khi bấm Xem để load dữ liệu Sổ nhập viện , Sổ xuất viện thì phần mềm báo lỗi
(dữ liệu tháng 01/2024, test dữ liệu BV khác cũng lỗi giống vậy)

![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/97272332/aa909321-2f69-4767-977a-e822452b153b)
![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/97272332/6ff79f0f-77d3-41e3-9054-f1e317b831d0)

**Comment by gh-dh-bot-01** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hospitalreports/115)

**Comment by vinh-dh** [comment]
Để a kiểm tra.

**Comment by chauthanhtra** [comment]
- Phần mềm Reports mới đã fix lỗi xem Sổ nhập viện, sổ xuất viện.
![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/97272332/331d5084-3dfc-4701-8ac2-a757cb5da7c1)
![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/97272332/12624d32-e6a2-451e-b4bb-0f090afd597d)

- Test dữ liệu bệnh nhân mới không phát hiện lỗi mới, bảng kê 6556, thu phí, XML xuất bình thường
![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/97272332/3de3d967-d118-4cc0-b825-2f90260aac41)
![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/97272332/79db9f37-c0ce-4d6f-9bd6-a1b3920321fd)
![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/97272332/517ec0ea-1b38-411c-aa39-25bf17be11f9)
![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/97272332/ef0bacf1-8160-4c02-a86c-a00cc45fd474)
![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/97272332/c54aafbd-f9e3-4922-a38d-3413ccfbcc17)
