### ISSUE TITLE
Lỗi - Lỗi Mã loại khám chữa bệnh XML 4210 trường hợp bệnh nội trú dưới 4h (BV Thanh Bình)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#120]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **05/07/2024**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **05/07/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_thanhbinh_maloai9_05072024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_thanhbinh_maloai9_05072024`](https://gofile.me/78TQg/bXKAI5VZG)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2018054253` - _**MaKB**_: `2406009765` - _**MaBA**_: `2024004881` _**NgayKCB**_: `26/06/2024` - _**MaPhong**_: `` - _**MaDV**_: `09` - _**ThangKT**_: `06` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
XML 4210 lỗi mã loại khám chữa bệnh trường hợp bệnh nhân nội trú dưới 4h.

* nhờ anh Fix lỗi sớm giúp để bệnh viện gửi dữ liệu tháng củ trong hôm nay.
```
![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/d90b1721-acad-4bed-9daa-09484787fb72)
![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/5375daa4-a5ad-4597-afdb-f4d9da14432d)
![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/44ac604b-0c52-45c5-b4cb-622590055cd6)

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-07-09**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by ongtrieuhau-dh** [comment]
Thử bản cũ xem được hông nhé @le-an-87

**Comment by le-an-87** [comment]
củ mới gì cũng 9 hà anh. mô tả đã là 9 rồi

**Comment by ongtrieuhau-dh** [comment]
Nhiều bệnh bị như vậy hông

**Comment by le-an-87** [comment]
khoảng hai ba chục cas a

**Comment by ongtrieuhau-dh** [comment]
Nếu đúng là 03, và có ngày vào nội trú phải không @le-an-87 ?

**Comment by ongtrieuhau-dh** [comment]
## HD.09 [^HD09]
-  ✔️ **Phê duyệt YC theo HD.08** 
-  👉 **Assign**: @vinh-dh 
-  👉 **Thực hiện các yêu cầu theo luồng công việc này**
-  📣 **Lưu ý khi tiếp nhận**: 

1. _Ghi nhận thời gian hoàn thành dự kiến, theo định dạng yyyy-MM-dd, và thời gian hoàn thành không được lớn hơn thời gian dự kiến ở HD.05_ 
2. _Trường hợp không tiếp nhận hoặc thời gian không đúng với thời gian dự kiến ở HD.05 phải nêu rõ lý do._
3. _Theo dõi vi phạm HD.04 của luồng công việc này theo_ **HD.04** [^HD04]
4. _Cập  nhật sản phẩm để giải quyết luồng công việc này, diễn giải đầy đủ chức năng mới, chỉnh sửa lỗi theo mẫu READMECODING.md khi push code, có kèm hình ảnh hoặc tài liệu xác định đã có các chức năng mới, chỉnh lỗi xong._


[^HD09]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút), Trách nhiệm: theo dõi đến khi Close Issue
[^HD04]: Nghĩa vụ: ghi nhận đầy đủ thông tin

**Comment by le-an-87** [comment]
VAS lại báo kiểu này rồi anh ơi.
Tạm thời khỏi chỉnh lại nhe anh @ongtrieuhau , anh @vinh-dh 
![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/2874ffef-5fb9-4ded-bd42-5e2f8b18213b)
