### ISSUE TITLE
Lỗi - XML 4210 và mẫu 79 không tính được tiền thanh toán nguồn khác (BV Thanh Bình)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#121]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **09/07/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87010`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV thanh Bình**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_thanhbinh_xml4210_tienkhac_09072024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_thanhbinh_xml4210_tienkhac_09072024`](https://gofile.me/78TQg/5T1foVgPn)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024001100` - _**MaKB**_: `2406006358` - _**MaBA**_: `N2024000340` _**NgayKCB**_: `18/06/2024` - _**MaPhong**_: `HIV` - _**MaDV**_: `10` - _**ThangKT**_: `06` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**MaHH**_: `AC34`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bệnh nhân sử dụng thuốc AC34 có cấu hình thanh toán nguồn khác
-> XML 4210 và mẫu 79 không đưa tiền cùng chi trả qua nguồn khác

* bảng kê thì đưa qua nguồn khác

```
> XML và mẫu 79
![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/fd596bfd-60e5-4e98-ad7e-5b2de14c210d)
![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/5c69a3c3-6ad7-4d39-9dad-530e1064fc5a)

>bảng kê và danh mục thuốc
![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/384528d9-1d1d-4b4f-8501-b28bfeeeba08)
![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/3eed5ee5-9dbf-4cde-ba00-e29985e6d064)

**Comment by vinh-dh** [comment]
Để a kiểm tra.

**Comment by vinh-dh** [comment]
Đã kiểm tra. Đây không phải lỗi. Do đây là BN HIV, chức năng báo cáo liên quan HIV hiện tại chỉ mở ra sử dụng đối với các BV có hợp đồng HIV.

**Comment by le-an-87** [comment]
anh @nghivanbi ơi coi chổ này giùm em

**Comment by nghivanbi** [comment]
ok anh yêu cầu mở chức năng báo cáo bệnh HIV cho Thanh Bình, này bv có hợp đồng.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Reports.exe v.3.24.0710.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FReportsexe%2F32407100-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FReportsexe%2F32407100-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FReportsexe%2F32407100-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: Mở chức năng báo cáo bệnh nhân HIV có thanh toán chi phí nguồn khác.

- ☑: https://github.com/dh-hos/To_Lap_Trinh/issues/462

- ☑: https://github.com/dh-hos/dhg.hospitalreports/issues/121

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vinh--dh-informational?logo=github)](https://github.com/vinh-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Reports.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by le-an-87** [comment]
Đã fix!
![ảnh](https://github.com/user-attachments/assets/733ea169-ecf2-42ff-abe8-78d0944908e9)
![ảnh](https://github.com/user-attachments/assets/e038cf5b-ad39-4f74-b459-4006e24ced51)
