### ISSUE TITLE
Lỗi - Gửi giấy KSK theo Đề án 06 bị double nhiều dòng.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalreports#122]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **10/07/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `51219`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PK Minh Quang**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_pkminhquang_qni_cks`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/1slbPkrN0)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024013258` - _**MaKB**_: `2407002235` - _**MaBA**_: `MaBA` _**NgayKCB**_: `10/07/2024` - _**MaPhong**_: `KB9` - _**MaDV**_: `10` - _**ThangKT**_: `07` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Thao tác sau khi ký xong, gửi len cổng, trên cổng xuất hiện 1 dòng ký đúng/serial đúng, nhưng kèm theo đó là có thêm 3 dòng thông tin giống nhau hoàn toàn, nên cổng sẽ đưa vào trạng thái **Hệ thống đa tiếp nhận, đang chờ xử lý**.

![image](https://github.com/dh-hos/dhg.hospitalreports/assets/99630883/deda752e-4611-479b-81c0-7d0c08d46623)

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Lỗi - Gửi giấy KSK theo Đề án 06 bị double nhiều dòng.
-  📆 **Thời gian hoàn thành :**  2024-07-14.

**Comment by lequocthong29** [comment]
Này nhờ bên cổng kiểm tra được không a @lqbinh1987.
Đã test thử bằng postman vẫn xuất hiện 4 dòng, không liên quan đến xữ lý trên phần mềm.
![image](https://github.com/user-attachments/assets/17fe7603-7dcb-4aea-88d7-1bf7062d0f3f)
![image](https://github.com/user-attachments/assets/8486fa6d-119b-48d4-8eb0-40e0c48c47c1)

**Comment by lqbinh1987** [comment]
Đã hoàn thành, đã thưc hiện gửi lên cổng thành công, các dòng khác bị lỗi là lỗi bên cổng BHXH(Nhân viên IT Phòng khám xác nhận).
![image](https://github.com/user-attachments/assets/cf85635f-cab2-4929-9558-589c8a1a9370)
