### ISSUE TITLE
Lỗi - XML 4210 tính sai tiền BNCCT và BHTT (BV Tim Mạch AG)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#123]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **07/08/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_yhct_ct_07082004`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_yhct_ct_07082004`](https://gofile.me/78TQg/xkL2ACrhI)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023014161` - _**MaKB**_: `2407007840` - _**NgayKCB**_: `08/07/2024 5:12:05 CH` - _**MaPhong**_: `PK01` - _**MaDV**_: `01` - _**ThangKT**_: `07` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
XML 4210 tính sai tiền BNCCT và BHTT
(bảng kê 6556 có thu cùng chi trả)

```
![ảnh](https://github.com/user-attachments/assets/676d6894-8860-46b1-844d-0417ffcf2c3c)
![ảnh](https://github.com/user-attachments/assets/f0caeda7-d93e-4547-8e8f-98868df5083f)

**Comment by vinh-dh** [comment]
✔️ Đã tiếp nhận.
👉 Để anh kiểm tra.

**Comment by vinh-dh** [comment]
@le-an-87 em kiểm tra lại dữ liệu. Anh chạy lên không thấy bệnh nào hết.

![image](https://github.com/user-attachments/assets/ad3cdb94-2a9c-4a30-af65-f0a523a5936d)

**Comment by vinh-dh** [comment]
> MaBN: 2023014161 - MaKB: 2407007840 - NgayKCB: 08/07/2024 5:12:05 CH - MaPhong: PK01 - MaDV: 01 - ThangKT: 07 - NamKT: 2024

![image](https://github.com/user-attachments/assets/22d5053f-27d4-40e3-bb4c-2d5c7572fcae)

Có lộn dữ liệu không? Ở trên để BV Tim Mạch AG, nhưng data là BV YHCT Cần Thơ?

**Comment by le-an-87** [comment]
em coppy nhằm tên data rồi anh ơi. để em tạo lại git khác.
