### ISSUE TITLE
Lỗi - XML 4210 tính sai tiền BNCCT và BHTT (BV Tim Mạch AG)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#124]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **07/08/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_timmachsg_reports_07082024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_timmachsg_reports_07082024`](https://gofile.me/78TQg/xkL2ACrhI)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023014161` - _**MaKB**_: `2407007840` - _**NgayKCB**_: `08/07/2024 5:12:05 CH` - _**MaPhong**_: `PK01` - _**MaDV**_: `01` - _**ThangKT**_: `07` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
XML 4210 tính sai tiền BNCCT và BHTT
(bảng kê 6556 có thu cùng chi trả)

```
![ảnh](https://github.com/user-attachments/assets/676d6894-8860-46b1-844d-0417ffcf2c3c)
![ảnh](https://github.com/user-attachments/assets/f0caeda7-d93e-4547-8e8f-98868df5083f)

**Comment by vinh-dh** [comment]
✔️ Đã tiếp nhận.
👉 Để anh kiểm tra.

**Comment by vinh-dh** [comment]
Không hiểu sao ca này đã in phiếu 01, nhưng cột `tongtienbh và tongtienbv đang = 0`.
![image](https://github.com/user-attachments/assets/a3106f7f-6b18-4cd0-935d-9936a83c878e)

Do `tongtienbh=0`, nên phần mềm tính theo công thức cũ lúc chưa áp dụng 4210. Phần công thức cũ để anh coi và fix lại. Còn lỗi in phiếu 01 rồi mà tongtienbh = 0 em kiểm tra nhé @le-an-87.

**Comment by le-an-87** [comment]
- ✔️ Đã tiếp nhận
- ⌛ Thời gian dự kiến hoàn thành kiểm tra: '12/08/2024'.
***
- Kiểm tra chức năng BLYC theo:
o Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
- Kiểm tra chức năng cơ bản của phân hệ trong qui trình khám chữa bệnh hoặc qui trình kho. Chứng minh bằng hình ảnh:
o Phiếu 01, 02, xuất XML.
o Nhập thuốc -> xuất thuốc -> tổng hợp.
o Có hình ảnh chứng mình cho việc kiểm tra này.
- File: copy sản phẩm đã kiểm thử thành công lên NAS: NAS\DuLieuCongTy\Modules -> Close Issue.
- Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

**Comment by le-an-87** [comment]
### **✔️KẾT QUẢ TEST**
***
> Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.
- Diễn giải lỗi:

- Hình ảnh lỗi:

> Hình ảnh Phiếu 01, 02, xuất XML.
![ảnh](https://github.com/user-attachments/assets/4409146e-04d7-494e-9115-c358028b430a)
![ảnh](https://github.com/user-attachments/assets/48ed163d-5b0f-4540-a6b5-bda1c20d40d0)

> Nhập thuốc -> xuất thuốc -> tổng hợp.

> Hình ảnh chứng mình cho việc kiểm tra này.
![ảnh](https://github.com/user-attachments/assets/7ced1b9a-7ffc-4f24-98bc-73f3bf341c0e)
> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by le-an-87** [comment]
### **HoànThành**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
