### ISSUE TITLE
Lỗi - Report xuất Excel theo 3360 theo Quyết định 4750 gửi cổng BH báo lỗi 

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitalreports#126]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ĐỨC**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **03/09/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `93102`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Số 10**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_so10_report4750`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/xqZFwubt1

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024040507` - _**MaKB**_: `2408018100` - _**MaBA**_: `2024004966` _**NgayKCB**_: `25/08/2024` - _**MaDV**_: `08` - _**ThangKT**_: `08` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Report xuất Excel theo 3360 của Quyết định 4750 gửi cổng báo lỗi sau:
![image](https://github.com/user-attachments/assets/d82d3152-fcb6-4b54-aeee-30d3a061e255)

Gửi cổng BH báo lỗi
![image](https://github.com/user-attachments/assets/7d95a717-5af5-410d-a434-fd81a67c3f3b)

**1. TRƯỜNG NGÀY SINH KHÔNG ĐÚNG ĐỊNH DẠNG**
-  ngay_sinh: đang dư 4 số 0 phía sau, chưa đúng theo [Mô tả XML130 - Module Reports xuất XML theo Quyết định 4750 và Mẫu C79 lấy từ dữ liệu XML4750](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML130/QD4570/M%C3%B4%20t%E1%BA%A3%20XML130%20-%20Module%20Reports%20xu%E1%BA%A5t%20XML%20theo%20Quy%E1%BA%BFt%20%C4%91%E1%BB%8Bnh%204750%20v%C3%A0%20M%E1%BA%ABu%20C79%20l%E1%BA%A5y%20t%E1%BB%AB%20d%E1%BB%AF%20li%E1%BB%87u%20XML4750.md)

![image](https://github.com/user-attachments/assets/ad848b29-b37b-480b-bb4f-989590f590fb)

Excel theo 3360 của Quyết định 4750
![image](https://github.com/user-attachments/assets/d813e76b-362a-469d-a812-fb05c29e64e2)

**2. TRƯỜNG MÃ LÝ DO VÀO VIỆN QUÁ DÀI**
-   ma_lydo_vv: đang lấy theo XML4750 chưa đúng với [Mô tả XML130 - Module Reports xuất XML theo Quyết định 4750 và Mẫu C79 lấy từ dữ liệu XML4750](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML130/QD4570/M%C3%B4%20t%E1%BA%A3%20XML130%20-%20Module%20Reports%20xu%E1%BA%A5t%20XML%20theo%20Quy%E1%BA%BFt%20%C4%91%E1%BB%8Bnh%204750%20v%C3%A0%20M%E1%BA%ABu%20C79%20l%E1%BA%A5y%20t%E1%BB%AB%20d%E1%BB%AF%20li%E1%BB%87u%20XML4750.md)
![image](https://github.com/user-attachments/assets/3a1c92fd-fee0-4341-b243-7adaa86ffe9d)

Excel theo 3360 của Quyết định 4750
![image](https://github.com/user-attachments/assets/170d40cd-34f7-4b7f-9291-04707cbd4b5e)

**Comment by vinh-dh** [comment]
✔️ Đã tiếp nhận.
👉 Xử lý:
> 1. TRƯỜNG NGÀY SINH KHÔNG ĐÚNG ĐỊNH DẠNG
- Cột ngày sinh để anh kiểm tra lại.
> 2. TRƯỜNG MÃ LÝ DO VÀO VIỆN QUÁ DÀI
- ❌Từ chối tiếp nhận, lý do: không sai mô tả❌

**Comment by hvtuan1987** [comment]
@vinh-dh Report đang lấy trường mã_lydo_vvien theo mô tả hiện tại của mình là đúng nhưng cổng hiện tại đang bắt trường này là lấy theo 4210 á. Nên có thể anh mô tả lại chổ này hoặc có tùy chọn cho đơn vị cấu hình á ! Tất cả các cơ sở đang gởi mẫu 3360 theo 4750 này là  đều bị lỗi hết á!

**Comment by vinh-dh** [comment]
> @vinh-dh Report đang lấy trường mã_lydo_vvien theo mô tả hiện tại của mình là đúng nhưng cổng hiện tại đang bắt trường này là lấy theo 4210 á. Nên có thể anh mô tả lại chổ này hoặc có tùy chọn cho đơn vị cấu hình á ! Tất cả các cơ sở đang gởi mẫu 3360 theo 4750 này là đều bị lỗi hết á!

Ok, nếu yêu cầu thay đổi mô tả cho phù hợp thì để anh điều chỉnh lại mô tả tại cột `ma_lydo_vvien` trong trường hợp này.

**Comment by vinh-dh** [comment]
Cập nhật [Mô tả XML130 - Module Reports xuất XML theo Quyết định 4750 và Mẫu C79 lấy từ dữ liệu XML4750](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML130/QD4570/M%C3%B4%20t%E1%BA%A3%20XML130%20-%20Module%20Reports%20xu%E1%BA%A5t%20XML%20theo%20Quy%E1%BA%BFt%20%C4%91%E1%BB%8Bnh%204750%20v%C3%A0%20M%E1%BA%ABu%20C79%20l%E1%BA%A5y%20t%E1%BB%AB%20d%E1%BB%AF%20li%E1%BB%87u%20XML4750.md):
- Điều chỉnh điều kiện cột `ngay_sinh` khi xuất dữ liệu `Excel 3360`, chỉ lấy 8 ký tự bên trái cột `bang1.ngay_sinh`.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Reports.exe v.3.24.0906.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FReportsexe%2F32409060-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FReportsexe%2F32409060-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FReportsexe%2F32409060-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Điều chỉnh điều kiện cột `ngay_sinh` khi xuất dữ liệu `Excel 3360`, chỉ lấy 8 ký tự bên trái cột `bang1.ngay_sinh`.

- ☑: https://github.com/dh-hos/dhg.hospitalreports/issues/126

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vinh--dh-informational?logo=github)](https://github.com/vinh-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Reports.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by minhduc2it** [comment]
**HOÀN THÀNH**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
--- 
Đã kiểm tra thành công (cột ngay_sinh khi xuất dữ liệu Excel 3360, chỉ lấy 8 ký tự bên trái cột bang1.ngay_sinh)
![image](https://github.com/user-attachments/assets/0c81f023-8f33-4721-b129-a09c119b6f1e)

**Comment by minhduc2it** [comment]
Data: duc_thuongthanh
Port: 5434
Link data: https://gofile.me/78TQg/gsjZ0xJDI
---
Report Excel CV3360 theo QĐ 4750 đang lấy trường ngay_sinh theo mô tả
Nhưng Đối với những BN chỉ có năm sinh gửi cổng báo lỗi
Cổng lấy trường ngay_sinh (chỉ có năm sinh) theo Excel CV3360 theo QĐ 4210

![image](https://github.com/user-attachments/assets/7a2c4d20-8a7e-448c-b811-f325031746dd)

Excel CV3360 theo QĐ 4750
![image](https://github.com/user-attachments/assets/9ef0a776-9332-4b2a-9508-7f73d9e6ae2c)

Excel CV3360 theo QĐ 4210
![image](https://github.com/user-attachments/assets/67e195bf-1cd2-4379-a334-295e42a432cc)

**Comment by vinh-dh** [comment]
✔️ Đã tiếp nhận.
👉 Xử lý: Anh bổ sung mô tả cho trường hợp BN chỉ có năm sinh.

**Comment by vinh-dh** [comment]
Cập nhật [Mô tả XML130 - Module Reports xuất XML theo Quyết định 4750 và Mẫu C79 lấy từ dữ liệu XML4750](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML130/QD4570/M%C3%B4%20t%E1%BA%A3%20XML130%20-%20Module%20Reports%20xu%E1%BA%A5t%20XML%20theo%20Quy%E1%BA%BFt%20%C4%91%E1%BB%8Bnh%204750%20v%C3%A0%20M%E1%BA%ABu%20C79%20l%E1%BA%A5y%20t%E1%BB%AB%20d%E1%BB%AF%20li%E1%BB%87u%20XML4750.md):
- Bổ sung điều kiện cột `ngay_sinh` khi xuất dữ liệu `Excel 3360`, chỉ lấy 4 ký tự bên trái cột `bang1.ngay_sinh` đối với người bệnh chỉ có năm sinh.
- Bổ sung điều kiện cột `ma_loaikcb` khi xuất dữ liệu `Excel 3360`. 
- Bổ sung điều kiện cột `ket_qua_dtri` khi xuất dữ liệu `Excel 3360`.
- Bổ sung điều kiện cột `ma_lydo_vvien` khi xuất dữ liệu `Excel 3360`. 

![image](https://github.com/user-attachments/assets/2f270d86-39a9-42c5-af05-3463fdcf730b)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Reports.exe v.3.24.0913.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FReportsexe%2F32409130-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FReportsexe%2F32409130-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FReportsexe%2F32409130-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: Bổ sung trường hợp xuất Excel 3360 người bệnh chỉ có năm sinh.

- ☑: https://github.com/dh-hos/To_Lap_Trinh/issues/577

- ☑: https://github.com/dh-hos/dhg.hospitalreports/issues/126

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vinh--dh-informational?logo=github)](https://github.com/vinh-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Reports.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by minhduc2it** [comment]
**HOÀN THÀNH**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
---
Đã thử Xuất C79 4750-4210 gửi cổng thành công
![image](https://github.com/user-attachments/assets/dbca7fc9-994c-43ea-9f23-7408f4bd376f)

![image](https://github.com/user-attachments/assets/af407ed9-8e01-4d89-b447-e579cda377bc)

![image](https://github.com/user-attachments/assets/2f475c9b-ce16-4ec8-83a7-3a9d3e98c1a8)
