### ISSUE TITLE
Yêu cầu - Thay đổi mô tả Mẫu C79 lấy từ dữ liệu XML4750 cho phù hợp với cổng BH

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitalreports#127]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ĐỨC**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **05/09/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `93102`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV số 10**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_so10_report4750`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/xqZFwubt1

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

[Theo Mô tả XML130 - Module Reports xuất XML theo Quyết định 4750 và Mẫu C79 lấy từ dữ liệu XML4750](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML130/QD4570/M%C3%B4%20t%E1%BA%A3%20XML130%20-%20Module%20Reports%20xu%E1%BA%A5t%20XML%20theo%20Quy%E1%BA%BFt%20%C4%91%E1%BB%8Bnh%204750%20v%C3%A0%20M%E1%BA%ABu%20C79%20l%E1%BA%A5y%20t%E1%BB%AB%20d%E1%BB%AF%20li%E1%BB%87u%20XML4750.md)

Report Excel CV3360 theo QĐ 4750 đang lấy trường mã_lydo_vvien theo mô tả trên, nhưng hiện tại cổng BH đang bắt trường này là lấy theo QĐ4210
Đề nghị thay đổi mô tả cho phù hợp với cổng BH
![image](https://github.com/user-attachments/assets/8ce1843f-9323-40ea-9f1a-e3c92369747b)

Yêu cầu thay đổi mô tả theo git này https://github.com/dh-hos/dhg.hospitalreports/issues/126

**Comment by le-an-87** [comment]
### **Trả lời vướng mắc**
Hiện tại nếu để trường ma_lydo_vvien =  ma_doi_tuong thì cổng bảo lỗi anh ơi
![ảnh](https://github.com/user-attachments/assets/0c770f4c-3921-4df1-b3b6-f2122c953777)

***

**Comment by le-an-87** [comment]
### **Trả lời vướng mắc**
anh xem có hỗ trợ cho bv chổ này không nhe anh @nghivanbi . bv cần để gửi mẫu 7980 anh ơi.
***

**Comment by nghivanbi** [comment]
❓ XÁC NHẬN ❓
---------------------------------------------------------------------
-  👉 **Assign**: 
-  📘 **Nội dung**: Cung cấp cụ thể một bệnh nhân sai @le-an-87, @minhduc2it  coi hiện mình gởi giá trị sao?

**Comment by minhduc2it** [comment]
Excel theo 3360 của Quyết định 4750
![image](https://github.com/user-attachments/assets/b8bb93db-af0e-455f-9585-7613797e1b9c)

Excel theo 3360 của Quyết định 4210
![image](https://github.com/user-attachments/assets/7529b1bb-0147-4b65-b137-73a46c17a1ed)

**Excel theo 3360 của Quyết định 4750 cột ma_lydo_vvien hiện tại cổng lấy theo 4210**

**Comment by nghivanbi** [comment]
### 👌 ĐỒNG Ý THỰC HIỆN 👌
---------------------------------------------------------------------
👉 **Phân công thực hiện**: @ongtrieuhau
⌛ **Hạn hoàn thành mong muốn**:
📘 **Nội dung**:
- Hiện cổng chưa theo kịp 4750, thực hiện mô tả tham số để hỗ trợ việc ghi nhận ma_lydo_vvien tại C79.

**Comment by ongtrieuhau-dh** [comment]
## HD.09 [^HD09]
-  ✔️ **Phê duyệt YC theo HD.08** 
-  👉 **Assign**: @vinh-dh 
-  👉 **Thực hiện các yêu cầu theo luồng công việc này**
-  📣 **Lưu ý khi tiếp nhận**: Đã có báo theo git này: [Hỗ trợ khách hàng - Xuất 3360 theo 4750 lỗi MA_LOAIKCB, MA_LYDO_VVIEN, KET_QUA_DTRI](https://github.com/dh-hos/To_Ho_Tro/issues/95)

1. _Ghi nhận thời gian hoàn thành dự kiến, theo định dạng yyyy-MM-dd, và thời gian hoàn thành không được lớn hơn thời gian dự kiến ở HD.05_ 
2. _Trường hợp không tiếp nhận hoặc thời gian không đúng với thời gian dự kiến ở HD.05 phải nêu rõ lý do._
3. _Theo dõi vi phạm HD.04 của luồng công việc này theo_ **HD.04** [^HD04]
4. _Cập  nhật sản phẩm để giải quyết luồng công việc này, diễn giải đầy đủ chức năng mới, chỉnh sửa lỗi theo mẫu READMECODING.md khi push code, có kèm hình ảnh hoặc tài liệu xác định đã có các chức năng mới, chỉnh lỗi xong._


[^HD09]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút), Trách nhiệm: theo dõi đến khi Close Issue
[^HD04]: Nghĩa vụ: ghi nhận đầy đủ thông tin

**Comment by vinh-dh** [comment]
Yêu cầu này đang trùng với [Hỗ trợ khách hàng - Xuất 3360 theo 4750 lỗi MA_LOAIKCB, MA_LYDO_VVIEN, KET_QUA_DTRI #95](https://github.com/dh-hos/To_Ho_Tro/issues/95)

**Comment by ongtrieuhau-dh** [comment]
### 📢 @vinh-dh 

- Thêm đây nữa nè: [Yêu cầu - Report form xuất dữ liệu XML 130 chỉnh lại một số cột khi xuất Excel 3360](https://github.com/dh-hos/Yeu_cau_ho_tro/issues/292)
- Chắc nhiều khách hàng đang vướng nên @vinh-dh  tranh thủ chỗ này

**Comment by vinh-dh** [comment]
Để anh tranh thủ.

**Comment by ongtrieuhau-dh** [comment]
## HD.09 [^HD09]
-  ✔️ **Phê duyệt YC theo HD.08** 
-  👉 **Assign**: @vinh-dh 
-  👉 **Thực hiện các yêu cầu theo luồng công việc này**
-  📣 **Lưu ý khi tiếp nhận**: Xem tổng hợp lại hết các Fields đang bị lỗi chỉnh luôn một lượt, mỗi git báo 1 số, làm git này, sẽ không đáp ứng git khác.

1. _Ghi nhận thời gian hoàn thành dự kiến, theo định dạng yyyy-MM-dd, và thời gian hoàn thành không được lớn hơn thời gian dự kiến ở HD.05_ 
2. _Trường hợp không tiếp nhận hoặc thời gian không đúng với thời gian dự kiến ở HD.05 phải nêu rõ lý do._
3. _Theo dõi vi phạm HD.04 của luồng công việc này theo_ **HD.04** [^HD04]
4. _Cập  nhật sản phẩm để giải quyết luồng công việc này, diễn giải đầy đủ chức năng mới, chỉnh sửa lỗi theo mẫu READMECODING.md khi push code, có kèm hình ảnh hoặc tài liệu xác định đã có các chức năng mới, chỉnh lỗi xong._


[^HD09]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút), Trách nhiệm: theo dõi đến khi Close Issue
[^HD04]: Nghĩa vụ: ghi nhận đầy đủ thông tin

**Comment by vinh-dh** [comment]
@ongtrieuhau-dh, tại bài này đã duyệt và tiếp nhận thời gian rồi: Yêu cầu này đang trùng với [Hỗ trợ khách hàng - Xuất 3360 theo 4750 lỗi MA_LOAIKCB, MA_LYDO_VVIEN, KET_QUA_DTRI #95](https://github.com/dh-hos/To_Ho_Tro/issues/95)

**Comment by vinh-dh** [comment]
@minhduc2it: Cột ngay_sinh em đang báo tại [Lỗi - Report xuất Excel theo 3360 theo Quyết định 4750 gửi cổng BH báo lỗi #126](https://github.com/dh-hos/dhg.hospitalreports/issues/126) thì vào đây báo tiếp.

**Comment by vinh-dh** [comment]
Cập nhật [Mô tả XML130 - Module Reports xuất XML theo Quyết định 4750 và Mẫu C79 lấy từ dữ liệu XML4750](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML130/QD4570/M%C3%B4%20t%E1%BA%A3%20XML130%20-%20Module%20Reports%20xu%E1%BA%A5t%20XML%20theo%20Quy%E1%BA%BFt%20%C4%91%E1%BB%8Bnh%204750%20v%C3%A0%20M%E1%BA%ABu%20C79%20l%E1%BA%A5y%20t%E1%BB%AB%20d%E1%BB%AF%20li%E1%BB%87u%20XML4750.md):
- Bổ sung điều kiện xuất Excel3360 theo 4750 và 4210.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Reports.exe v.3.24.0914.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FReportsexe%2F32409140-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FReportsexe%2F32409140-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FReportsexe%2F32409140-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: Bổ sung xuất Excel 3360 tại form XML4750 theo 4750 và 4210. ![image](https://github.com/user-attachments/assets/0b705eaf-3075-4bef-abbe-b6bec849f7ca)

- ☑: https://github.com/dh-hos/Yeu_cau_ho_tro/issues/292

- ☑: https://github.com/dh-hos/dhg.hospitalreports/issues/127

- ☑: https://github.com/dh-hos/To_Ho_Tro/issues/95

- ☑: https://github.com/dh-hos/To_Lap_Trinh/issues/577

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vinh--dh-informational?logo=github)](https://github.com/vinh-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Reports.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by minhduc2it** [comment]
**HOÀN THÀNH**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
---
Các yêu cầu đã kiểm tra hoàn thành
![image](https://github.com/user-attachments/assets/3a3f575a-2b85-4a4f-9404-0fd8cd786e76)
