### ISSUE TITLE
Lỗi - Report vẫn hiển thị thông tin xuất dữ liệu theo130 (4750) của bệnh nhân khi đã mở khóa trên Printer

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalreports#128]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **02/09/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Trung tâm y tế huyện Thạnh Trị**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbthanhtri_loinhapvien`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/TeBCuf3oO)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024000001` - _**MaKB**_: `2409000142` - _**MaBA**_: `MaBA` _**NgayKCB**_: `04/09/2024` - _**MaPhong**_: `01` - _**MaDV**_: `10` - _**ThangKT**_: `09` - _**NamKT**_: `2024`

Bệnh nhân ngoại trú khi in bảng kê thì Admin xem XML theo 4750 có thông tin bệnh nhân và Report  xem XML 130 (theo Quyết định 4750) đều có thông tin bệnh nhân như nhau. Nhưng khi Printer mở khóa thì lúc này trên Report xem XML 130 (4750) vẫn còn thông tin bệnh nhân dẫn đến lệch số lượng bệnh nhân trên Admin và trên Report. Do đơn vị mở khóa quên in lại hoặc vì lý do khác đơn vị hủy hồ sơ không thanh toán BHYT nữa nên hiện tại đa số các đơn vị đều lệch số lệch số liệu khi đối chiếu giữa XML admin và 3360 theo 4750. 
Nhờ các anh có giải pháp để hỗ trợ đơn các đơn vị nhanh chóng báo cáo liệu 3360 theo 4750.

**Comment by vinh-dh** [comment]
Xem hỗ trợ trường hợp này dùm anh nhé @ongtrieuhau-dh.

**Comment by ongtrieuhau-dh** [comment]
### ✅ TỔ LẬP TRÌNH - HOÀN THÀNH ✅
-  📣 **Nhờ kiểm tra sản phẩm**: @hvtuan1987 
- Đã cập nhật chức năng theo Git này [💼 Printer - Thực hiện xóa hồ sơ XML4750 khi thực hiện mở khóa phiếu 01⏳Dự kiến : 2024-09-11](https://github.com/dh-hos/To_Lap_Trinh/issues/639)
- Theo luồng công việc [Yêu cầu - Hỗ trợ lại cách lấy dữ liệu 4750 bị double nhiều dòng](https://github.com/dh-hos/To_Lap_Trinh/issues/628)

**Comment by hvtuan1987** [comment]
## 📣📣 @ongtrieuhau-dh 
Xác nhận Mở khóa Printer XML130 và XML 4210trên Report đã lấy đúng
![image](https://github.com/user-attachments/assets/a48ade07-6500-4bd3-b6c9-cf419f130b83)
