### ISSUE TITLE
Lỗi - XML1 4750 lệch tiền giữa Reports và admin (BV Ô Môn)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#131]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **17/09/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_omon_lech_xml_amin_reports_13092024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_omon_lech_xml_amin_reports_13092024`](https://gofile.me/78TQg/10ttcMTww)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024011906` - _**MaKB**_: `2408028985` - _**MaBA**_: `2024011312` _**NgayKCB**_: `01/09/2024 8:15:00 SA` - _**MaPhong**_: `29` - _**MaDV**_: `29` - _**ThangKT**_: `09` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
XML1 4750 lệch tiền so với xml xuất tại module admin
và tiền thuốc xml1 lệch so với xml2

```
![ảnh](https://github.com/user-attachments/assets/85d61867-8ad3-4496-9d1d-2aa71eb7f205)
![ảnh](https://github.com/user-attachments/assets/18a4e4f4-3d1a-406e-9e0c-4990f263cf6a)
![ảnh](https://github.com/user-attachments/assets/a8e9043f-b7a2-4da0-8cdf-44aa7060296c)

**Comment by vinh-dh** [comment]
@ongtrieuhau-dh em kiểm tra trường hợp này dùm anh nhé!

**Comment by vinh-dh** [comment]
À, cấu trúc dữ liệu của BV chưa thay đổi:
![image](https://github.com/user-attachments/assets/f5704251-0267-48a2-b70c-21ec12ce4657)

**Comment by vinh-dh** [comment]
Cập nhật cấu trúc:
![image](https://github.com/user-attachments/assets/992e23d3-4957-4787-b0ea-5e7cd68a2ee8)

**Comment by vinh-dh** [comment]
> Cập nhật cấu trúc:
> ![image](https://github.com/user-attachments/assets/992e23d3-4957-4787-b0ea-5e7cd68a2ee8)

Fix lỗi trên: lưu ý chạy script trên trước khi chạy script này
![image](https://github.com/user-attachments/assets/203ab244-4218-49ec-bc55-04cfc5d64cf5)

**Comment by le-an-87** [comment]
### **Trả lời vướng mắc**
Bệnh nào lệch thì báo lại để cập nhật script hay sao anh @vinh-dh 
***

**Comment by vinh-dh** [comment]
Đúng rồi.

Đây là script đối với BN em báo ở trên:
> ![image](https://github.com/user-attachments/assets/203ab244-4218-49ec-bc55-04cfc5d64cf5)

**Comment by le-an-87** [comment]
### **Trả lời vướng mắc**
bệnh nào lỗi thì phải trích dữ liệu báo anh xem hay cần thông tin gì không?
***

**Comment by vinh-dh** [comment]
Giải pháp tạm thời là vậy. Còn cần hỗ trợ nhiều bệnh nhân thì @ongtrieuhau em có giải pháp nào không?

**Comment by vinh-dh** [comment]
Vào chức năng `[Kiểm tra chi phí so với XML130]` của form xuất `XML4210` (chọn hồ sơ cần điều chỉnh), rồi vào tiếp chức năng `[Kiểm tra hồ sơ đang chọn]` để cập nhật lại dữ liệu `XML4750`.
![image](https://github.com/user-attachments/assets/77b2a3fc-8c20-4f5a-85b0-1e3cec14dd1b)

**Comment by le-an-87** [comment]
### **✔️KẾT QUẢ KIỂM TRA SẢN PHẨM**
***
> Hình ảnh chứng mình cho việc kiểm tra này.
![ảnh](https://github.com/user-attachments/assets/dd2a7376-8ee6-45ec-a88a-291a5a5095d2)

> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by le-an-87** [comment]
### **HoànThành**
Đã fix lỗi bệnh nhân theo dữ liệu báo.
***
- Tiến hành hỗ trợ khách hàng.
