### ISSUE TITLE
💼 Prescription - Thực hiện kiểm tra nguyên nhân bnnoitru có 2 dòng cùng makb⏳Dự kiến:  2024-10-09

### ISSUE THREAD

**Issue by ongtrieuhau-dh** [dh-hos/dhg.hospitalreports#136]
## HD.09 [^HD09]
-  ✔️ **Phê duyệt YC theo HD.08** 
-  👉 **Assign**: @lequocthong29 
-  👉 **Thực hiện các yêu cầu theo luồng công việc này**
-  📣 **Lưu ý khi tiếp nhận**: Kiểm tra xem nguyên nhân tại sao trong ***`current.bnnoitru`*** có 2 dòng cùng ***`makb`***. ![](https://i.imgur.com/orA4B0Q.png). ***Nếu không tìm được nguyên nhân thì phải chứng minh bản mới nhất khi xử lý nhập viện không bị tình trạng này.*** 

1. _Ghi nhận thời gian hoàn thành dự kiến, theo định dạng yyyy-MM-dd, và thời gian hoàn thành không được lớn hơn thời gian dự kiến ở HD.05_ 
2. _Trường hợp không tiếp nhận hoặc thời gian không đúng với thời gian dự kiến ở HD.05 phải nêu rõ lý do._
3. _Theo dõi vi phạm HD.04 của luồng công việc này theo_ **HD.04** [^HD04]
4. _Cập  nhật sản phẩm để giải quyết luồng công việc này, diễn giải đầy đủ chức năng mới, chỉnh sửa lỗi theo mẫu READMECODING.md khi push code, có kèm hình ảnh hoặc tài liệu xác định đã có các chức năng mới, chỉnh lỗi xong._

[^HD09]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút), Trách nhiệm: theo dõi đến khi Close Issue
[^HD04]: Nghĩa vụ: ghi nhận đầy đủ thông tin

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Thực hiện các yêu cầu theo luồng công việc này.
-  📆 **Thời gian hoàn thành :**  2024-10-09.

**Comment by lequocthong29** [comment]
- Đã kiểm tra Prescription khi xử lý Nhập viện không xuất hiện tình trạng bnnoitru có 2 dòng cùng makb

https://github.com/user-attachments/assets/52f74d3d-eb70-4935-980d-8bbdfd454f62

**Comment by ongtrieuhau-dh** [comment]
## <sub>📢 @lequocthong29  </sub>

- OK
