### ISSUE TITLE
Lỗi - XUẤT BÁO CÁO 130 - XML3.MA_VAT_TU LẤY SAI GIÁ TRỊ CỦA VẬT TƯ CÙNG TÊN

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hospitalreports#137]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HOÀ**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **09/10/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BVĐK H.THẠNH TRỊ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_thanhtri_full_24092024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/Oi8YIgvrM)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024010488` - _**MaKB**_: `MaKB` - _**MaBA**_: `2024007054` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `02` - _**ThangKT**_: `08` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

XML3.MA_VAT_TU lấy giá trị không đúng với mahh 

![image](https://github.com/user-attachments/assets/6e600380-1922-4491-8f2a-3476b6295dc8)
![image](https://github.com/user-attachments/assets/41ccfc99-5bf4-4b12-8af2-453f006ab38c)

130 đang lấy lên giá trị của 1 vật tư cùng tên
![image](https://github.com/user-attachments/assets/32e7f3e3-7cb5-4bfe-bf72-d3c3a37c5c97)
![image](https://github.com/user-attachments/assets/8100c802-6896-4b90-8736-75111018746c)

cùng hồ sơ đó nhưng xuất 4750 thì đúng với mahh
![image](https://github.com/user-attachments/assets/dfcf3f6a-a53d-4d90-9b99-5c6bb9b1cbbe)

em kiểm tra cũng thấy trong dữ liệu cũng ghi nhận sai giá trị
![image](https://github.com/user-attachments/assets/2385012e-b58d-4015-9d5e-f8db7ea01ee2)

✴️ Fix lấy đúng giá trị theo mahh dùm em.
✴️ Hỗ trợ cập nhật lại các giá trị đang bị sai theo trường hợp trên

**Comment by ongtrieuhau-dh** [comment]
## <sub>📢 @nqhoa1005  </sub>

- Dùng chức năng Kiểm tra sai chi phí để lưu lại XML47750 mới nhé

**Comment by nqhoa1005** [comment]
✅ Đã hỗ trợ
![image](https://github.com/user-attachments/assets/2c10156b-0a91-47fe-9428-3d799a12d363)
