### ISSUE TITLE
Lỗi - CHỨC NĂNG KIỂM TRA CẬP NHẬT CHI PHÍ 4210 CẬP NHẬT THIẾU HỒ SƠ NGOẠI TRÚ

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hospitalreports#141]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HOÀ**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **16/10/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BVĐK H.THẠNH TRỊ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_dbthanhtri2018006717_xuatxml`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/37sa7yvP1)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2018006717` - _**MaKB**_: `2410005372` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Printer vừa qua in bảng kê lỗi có 1 số hồ sơ ngoại trú không lên được XML 4750 khi chạy cập nhật chí phí từ 4210 vẫn không có trên 4750 và 130
![image](https://github.com/user-attachments/assets/e96aa5bd-e9f3-46fe-b71b-74e6d6f69373)

Đã chạy các chức năng cập nhật 
![image](https://github.com/user-attachments/assets/f57cfb7c-900d-41c9-8e91-0da99a1c2a5e)
![image](https://github.com/user-attachments/assets/6205ff40-6a67-489d-9fc0-40e1144387a4)

4750 và 130 vẫn chưa có hồ sơ
![image](https://github.com/user-attachments/assets/62c50b49-bda8-4f61-8108-1207900c7c88)
![image](https://github.com/user-attachments/assets/65d7011c-5d90-41d6-aabd-71214d6d8e13)

✴️ kiểm tra lại fix trường hợp này gấp dùm em để các đơn vị chạy lên gửi hồ sơ XML

**Comment by vinh-dh** [comment]
@ongtrieuhau em kiểm tra trường hợp này dùm anh nhé!

**Comment by ongtrieuhau-dh** [comment]
## <sub>📢 @nqhoa1005  </sub>

- Nhờ kiểm tra xem trong thư mục cài đặt có thông tin lỗi của hồ sơ này không
- Nếu có Gửi lên đây để Tổ Lập trình kiểm tra lại

**Comment by nqhoa1005** [comment]
❗❗ **TRAO ĐỔI** ❗❗
---
✳️Trường hợp này là không có XML khi xuất 4750 chứ không phải gửi cổng, nếu có ghi log thì cụ thể là thư mục cài đặt của Admin hay Report anh?
- Em vừa thao tác chạy cập nhật xong rồi chụp mới báo lên thì kiểm cả 2 thư mục đều không có file log hôm nay.

**Comment by ongtrieuhau-dh** [comment]
## <sub>📢 @nqhoa1005  </sub>

- ![image](https://github.com/user-attachments/assets/d7dec826-e3b1-49db-bf3f-43895cfa060f)

**Comment by nqhoa1005** [comment]
📢anh @ongtrieuhau-dh 
---
[Log-20241016.txt](https://github.com/user-attachments/files/17390728/Log-20241016.txt)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalAdmin.exe v.3.24.1016.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32410161-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32410161-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32410161-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: **💼**: **_Lỗi - CHỨC NĂNG KIỂM TRA CẬP NHẬT CHI PHÍ 4210 CẬP NHẬT THIẾU HỒ SƠ NGOẠI TRÚ_**

- 🐛: Chỉnh lỗi khi thực hiện thao tác Đối soát hồ sơ ![](https://i.imgur.com/OpDeZn9.png) ![](https://i.imgur.com/TbFcgdH.png)

- ☑: https://github.com/dh-hos/dhg.hospitalreports/issues/141

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalAdmin.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Reports.exe v.3.24.1016.2 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FReportsexe%2F32410162-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FReportsexe%2F32410162-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FReportsexe%2F32410162-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: **💼**: **_Lỗi - CHỨC NĂNG KIỂM TRA CẬP NHẬT CHI PHÍ 4210 CẬP NHẬT THIẾU HỒ SƠ NGOẠI TRÚ_**

- 🐛: Chỉnh lỗi khi thực hiện thao tác Đối soát hồ sơ ![](https://i.imgur.com/OpDeZn9.png) ![](https://i.imgur.com/TbFcgdH.png)

- ☑: https://github.com/dh-hos/dhg.hospitalreports/issues/141

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Reports.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by nqhoa1005** [comment]
✔️ **ĐÃ TIẾP NHẬN PHIÊN BẢN MỚI** 
👉 **Vui lòng chờ test lại**

**Comment by nqhoa1005** [comment]
❌ **CHƯA ĐẠT YÊU CẦU** ❌ 
✔️ 
- ❗❗ Phát sinh hồ sơ có trên 130 và 4210 nhưng vẫn thiếu trên 4750 


✳️ Thông tin test : 
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BVĐK H.THẠNH TRỊ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_dbthanhtri2018006717_xuatxml`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/BY0O0jHXm)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022006226` - _**MaKB**_: `2410005450` - _**MaBA**_: `MaBA` _**NgayKCB**_: `15/10/2024` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `10` - _**NamKT**_: `2024`
---

Test trực tiếp với đơn vị thì vẫn sót 1 số ca không có khi xuất 4750
- Đã chạy cập nhật chi phí và Đối soát hồ sơ vẫn không có
![image](https://github.com/user-attachments/assets/e000f1ee-b227-4a0e-9490-802f04478b3e)
![image](https://github.com/user-attachments/assets/0e75674f-7c9b-4a07-a07c-56181a597a84)

Đối soát
![image](https://github.com/user-attachments/assets/83a79730-47d3-4596-97a8-25c4fa1a6e53)

Cập nhật chi phí 4210
![image](https://github.com/user-attachments/assets/35413f8e-0e8a-48da-8df8-8683b9e27c16)

Xuất lại 4750 
![image](https://github.com/user-attachments/assets/269582f5-869c-4a1a-adaf-3450bc9d91eb)

✔️ Đã test thử nếu in lại lần 2 trên Printer thì sẽ có trên 4750

- Ngày 15/10 thiếu tổng cộng 5 hồ sơ :

94006_2024_10_2022006226_2410005450
94006_2024_10_2021001188_2410005447
94006_2024_10_2012011175_2410005602
94006_2024_10_2022008492_2410005613
94006_2024_10_2011011795_2410005570

---
- ✳️ Lần test : 1
- ❗❗ Dừng test các chức năng liên quan.

**Comment by ongtrieuhau-dh** [comment]
## <sub>📢 @nqhoa1005  </sub>

- Tổ Lập trình sẽ kiểm lại các trường hợp này 
```
94006_2024_10_2022006226_2410005450
94006_2024_10_2021001188_2410005447
94006_2024_10_2012011175_2410005602
94006_2024_10_2022008492_2410005613
94006_2024_10_2011011795_2410005570
```

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ❌ **Từ chối tiếp nhận** 
- 📣 **Nguyên nhân**: @nqhoa1005 @lqbinh1987 @nghivanbi  ***Dữ liệu không đủ để kiểm tra*** ![](https://i.imgur.com/ZEo0Os9.png)


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.] Nghĩa vụ: ghi nhận vi phạm nếu có tại HD.04, phản hồi
đủ thông tin

**Comment by nqhoa1005** [comment]
Em bổ sung thông tin dữ liệu
✳️ Thông tin test : 
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BVĐK H.THẠNH TRỊ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_dbthanhtri_102024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/BY0O0jHXm)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022006226` - _**MaKB**_: `2410005450` - _**MaBA**_: `MaBA` _**NgayKCB**_: `15/10/2024` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `10` - _**NamKT**_: `2024`
---

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalAdmin.exe v.3.24.1017.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32410170-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32410170-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32410170-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: **💼**: **_Lỗi - CHỨC NĂNG KIỂM TRA CẬP NHẬT CHI PHÍ 4210 CẬP NHẬT THIẾU HỒ SƠ NGOẠI TRÚ_**

- 🐛: ***Chỉnh lỗi chức năng Đối soát hồ sơ giữa 4210 và 4750 không có hồ sơ trên bảng kê 4750 trên module Admin*** ![](https://i.imgur.com/T3iIhTl.png)

- ☑: https://github.com/dh-hos/dhg.hospitalreports/issues/141#issuecomment-2418348830

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalAdmin.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Reports.exe v.3.24.1017.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FReportsexe%2F32410170-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FReportsexe%2F32410170-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FReportsexe%2F32410170-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: **💼**: **_Lỗi - CHỨC NĂNG KIỂM TRA CẬP NHẬT CHI PHÍ 4210 CẬP NHẬT THIẾU HỒ SƠ NGOẠI TRÚ_**

- 🐛: ***Chỉnh lỗi chức năng Đối soát hồ sơ giữa 4210 và 4750 không có hồ sơ trên bảng kê 4750 trên module Admin*** ![](https://i.imgur.com/T3iIhTl.png)

- ☑: https://github.com/dh-hos/dhg.hospitalreports/issues/141#issuecomment-2418348830

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Reports.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by nqhoa1005** [comment]
✔️ **ĐÃ TIẾP NHẬN PHIÊN BẢN MỚI** 
👉 **Vui lòng chờ test lại**

**Comment by nqhoa1005** [comment]
❗❗ **TRAO ĐỔI** ❗❗
✳️anh @ongtrieuhau-dh chạy lại tool trên 130 và 4210 số lượng hồ sơ đã khớp nhưng có ghi nhận lỗi.
Check dùm em xem lỗi này nếu có ảnh hưởng thì fix luôn ngược lại thì em đóng Git nhé
![image](https://github.com/user-attachments/assets/b4797eb1-56d2-4bf5-a556-1d12dcb3ea28)

[Log-20241017.txt](https://github.com/user-attachments/files/17407394/Log-20241017.txt)

**Comment by ongtrieuhau-dh** [comment]
## <sub>📢 @nqhoa1005  </sub>

- Chờ Tổ lập trình kiểm tra lại nhé, cho xin thông tin dữ liệu và những hồ sơ nào bị giống vậy nhé.

**Comment by nqhoa1005** [comment]
✳️ Thông tin test : 
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BVĐK H.THẠNH TRỊ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_dbthanhtri_102024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/BY0O0jHXm)

Chổ này em chạy ngày 15/10 lại cho khớp hồ sơ thì thấy phát sinh lỗi
- 94006_2024_10_2018000774_2410001102_2024007935
![image](https://github.com/user-attachments/assets/9ff446ff-9cd5-45e4-a479-c0863c5da994)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Reports.exe v.3.24.1017.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FReportsexe%2F32410171-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FReportsexe%2F32410171-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FReportsexe%2F32410171-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: **💼**: **_Lỗi - CHỨC NĂNG KIỂM TRA CẬP NHẬT CHI PHÍ 4210 CẬP NHẬT THIẾU HỒ SƠ NGOẠI TRÚ_**

- ✨: Chỉnh lỗi khi Đối soát hồ sơ đối Nội trú ![](https://i.imgur.com/YHMXGYD.png)

- ☑: https://github.com/dh-hos/dhg.hospitalreports/issues/141

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Reports.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalAdmin.exe v.3.24.1017.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32410171-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32410171-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32410171-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: **💼**: **_Lỗi - CHỨC NĂNG KIỂM TRA CẬP NHẬT CHI PHÍ 4210 CẬP NHẬT THIẾU HỒ SƠ NGOẠI TRÚ_**

- ✨: Chỉnh lỗi khi Đối soát hồ sơ đối Nội trú ![](https://i.imgur.com/YHMXGYD.png)

- ☑: https://github.com/dh-hos/dhg.hospitalreports/issues/141

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalAdmin.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by nqhoa1005** [comment]
❗❗ Còn lỗi tương tự với 1 hồ sơ ngoại trú nữa anh @ongtrieuhau-dh 
- 94006_2024_10_2018005140_2410006056
![image](https://github.com/user-attachments/assets/2bc568a4-4a55-4a93-a396-73c6d4ac7119)
![image](https://github.com/user-attachments/assets/2287f642-6e52-45a0-ab92-267ec3641b78)
![image](https://github.com/user-attachments/assets/bf3a8c04-0def-4f22-94a5-0dda09879555)

[Log-20241017.txt](https://github.com/user-attachments/files/17409250/Log-20241017.txt)

---
- ✳️ Lần test : 3
- ❗❗ Dừng test các chức năng liên quan.

**Comment by ongtrieuhau-dh** [comment]
## <sub>📢 @nqhoa1005  </sub>

- Trích dữ liệu bệnh nhân này giúp Tổ Lập trình

**Comment by nqhoa1005** [comment]
👉Link trích theo mabn
https://gofile.me/78TQg/m9r8xPH2e

**Comment by ongtrieuhau-dh** [comment]
## <sub>📢 @nqhoa1005  </sub>

- ***Trường hợp này do nhập cân nặng sai, nhờ chỉnh lại rồi chạy lại Chức năng Đối soát.*** ![](https://i.imgur.com/1pPfksq.png)

**Comment by nqhoa1005** [comment]
✅ HOÀN THÀNH
👉 Đã khớp hồ sơ khi chạy các tool hỗ trợ, lấy đủ các hồ sơ ngoại trú do Printer lỗi ở bản trước
![image](https://github.com/user-attachments/assets/3e1f9591-7fb2-4221-8b2c-c5082b4a0629)
![image](https://github.com/user-attachments/assets/c4978570-2edc-4f27-85a4-18baa0b50c41)
![image](https://github.com/user-attachments/assets/68764318-af55-4e9d-b7fb-d558c116ab79)
![image](https://github.com/user-attachments/assets/4d9cdfc0-50d8-4c56-ad29-bbf7c2d5f643)
![image](https://github.com/user-attachments/assets/bd705b08-5409-4bfb-b185-c80dd782472d)


---
✳️ Lần test : 4
