### ISSUE TITLE
Yêu cầu - Hỗ trợ mẫu Báo cáo đặc thù BV Da Liễu Đồng Tháp

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalreports#16]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **07/11/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87190`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện Da Liễu Đồng Tháp**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_dalieudt`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

Bệnh viện yêu cầu hỗ trợ mẫu Báo cáo hoạt động khám chữa bệnh theo nhóm ICD đặc thù 
(Mẫu này BV gởi hàng tháng về Bệnh viện Da Liễu Trung ương)

Các nhóm bệnh đang lấy theo nhóm bệnh trên admin (Nhóm này Bv sẽ cấu hình theo tên nhóm riêng)
Chủ yếu BV cần hỗ trợ các số liệu trong khung bôi đỏ (Của phần I), Phần II hỗ trợ điền tên như mẫu (Hỗ trợ xuất Excel mẫu này, các số liệu Phần II BV tự điền)
![image](https://user-images.githubusercontent.com/97272364/200210648-d8777138-d7a2-4126-9538-9e7530f4a2a4.png)

Link Full mẫu kèm theo á !
https://docs.google.com/spreadsheets/d/16tRx4cjO-ZCyHW_Fm9OO3ktR5N0RYkXQ/edit#gid=1754328067

```

**Comment by vinh-dh** [comment]
Báo cáo lượt ngoại trú thì hiện tại phần ngoại trú có rồi đó @hvtuan1987. 

Còn lượt theo bệnh ICD cụ thể thì em nói BV vào các mẫu như hình chỗ này cấu hình là nó có số liệu chứ gì.
![image](https://user-images.githubusercontent.com/112069710/200212717-a0fc8f54-aa9e-487b-98b5-efd6400b7f9e.png)

**Comment by vinh-dh** [comment]
Cần thiết thì đợi a bớt các công việc của các dự án khác thì anh nghiên cứu làm.

**Comment by hvtuan1987** [comment]
ok anh !
Em gởi lại link mẫu 
https://docs.google.com/spreadsheets/d/16tRx4cjO-ZCyHW_Fm9OO3ktR5N0RYkXQ/edit#gid=1754328067

**Comment by vinh-dh** [comment]
[SetupHospitalReport20221111](https://www.fshare.vn/file/W85PVYYPB6OK)

- Bổ sung menu: 
![image](https://user-images.githubusercontent.com/112069710/201287531-9d7c39c6-8a38-4859-abe2-62f5165dbfe8.png)

- Form báo cáo. Click vào các link (màu xanh tương ứng) để cấu hình bệnh tương ứng:
![image](https://user-images.githubusercontent.com/112069710/201287642-1572e384-fdd8-43fc-8f7f-002c10366b8a.png)

**Comment by hvtuan1987** [comment]
ok anh !

**Comment by vinh-dh** [comment]
Fix 1 số lỗi liên quan: [SetupHospitalReport20221221](https://www.fshare.vn/file/J9EYDP7KYTZ7)
