### ISSUE TITLE
Lỗi - Báo cáo tình hình bệnh tật tử vong

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalreports#17]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **09/11/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92127`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Hòa Hảo CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_hoahao_07_11`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `11` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Khi Báo cáo tình hình bệnh tật tử vong, lấy số liệu không hiển thị hết các mã bệnh đã được khám.

![image](https://user-images.githubusercontent.com/99630883/200714039-62cd6fd3-0fe9-484b-8535-d6e316c9a7e8.png)
![image](https://user-images.githubusercontent.com/99630883/200714070-e8b421f6-db86-471b-84d5-8d62bef62678.png)

Và hiển thị không đúng mã bệnh, tên bệnh khi click vào link số liệu. 
![image](https://user-images.githubusercontent.com/99630883/200714094-b02f05ab-75c1-463b-ac96-aa1bd46171d4.png)
![image](https://user-images.githubusercontent.com/99630883/200714105-32c0291f-cb9b-474d-9c63-7756a457cc10.png)

**Comment by vinh-dh** [comment]
Data bệnh viện này bị sai giá trị ma15 của I10, nên nó load dữ liệu bị sai.
![image](https://user-images.githubusercontent.com/112069710/200723342-ec94eef5-a1ca-4be3-95dd-f1edf22c4384.png)

Em nói BV lên Admin chạy script set lại nhe!

**Comment by vinh-dh** [comment]
Fix lỗi lệch giữa tổng hợp với chi tiết ở báo cáo này nhe @lqbinh1987 => [SetupHospitalReport20221110](https://www.fshare.vn/file/NXHAQLHCXG7A)
