### ISSUE TITLE
Lỗi - Bệnh nhân có thời gian điều trị trên 4h nhưng xml xuất ma_loai_kcb =9

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#19]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **18/11/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_lapvo_guitudong`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2020013925` - _**MaKB**_: `2211009133` - _**MaBA**_: `2022010060` _**NgayKCB**_: `17/11/2022` - _**MaDV**_: `CC` - _**ThangKT**_: `11` - _**NamKT**_: `2022`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bệnh nhân nội trú có thời gian điều trị lớn hơn 4h nhưng xml vẫn xuất ma_loai_kcb = 9
Ngày vào: 20221116 20:15 
Ngày ra:  20221117 00:30

```
![image](https://user-images.githubusercontent.com/96155021/202608324-166171bd-cb2c-4b4c-88bd-7bb162b855a8.png)
Mô tả cv 3788
![image](https://user-images.githubusercontent.com/96155021/202608527-6a228b2b-ede0-4219-8a04-980b9075cc81.png)

**Comment by vinh-dh** [comment]
[SetupHospitalReport20221118](https://www.fshare.vn/file/DNV9ACNXIGIV)

**Comment by le-an-87** [comment]
đã fix!
