### ISSUE TITLE
Yêu cầu - Sổ Vi Sinh & sổ Tế bào vi sinh theo Quyết định số số 4069/2001/QĐ-BYT

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#2]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **19/08/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_bvhongngu_sosinhhoa`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [``](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
Bv Hồng ngự đề nghị bổ sung sổ xét nghiệm vi sinh và sổ xét nghiệm tế bào máu ngoại vi chổ Labotory mình có bổ sung thêm không anh!

```
sổ vi sinh
![image](https://user-images.githubusercontent.com/96155021/185585826-fc290c60-77e2-4b8c-989b-6138938a68ca.png)
sổ tế bào máu ngoại vi
![image](https://user-images.githubusercontent.com/96155021/185585897-60de060a-2f1e-4def-b17e-7d274763a349.png)

link mẫu sổ:
https://kcb.vn/thu-vien-tai-lieu/quyet-dinh-so-so-4069-2001-qd-byt-ngay-28-9-2001-cua-bo-y-te.html

**Comment by nvvinh-dh** [comment]
Không nhé! Vì rất nhiều thông tin ở 2 sổ này hiện tại phần mềm không có quản lý.

[So XN vi sinh.pdf](https://github.com/dh-hos/dhg.hospitalreports/files/9380887/So.XN.vi.sinh.pdf)
[So XNTB mau ngoai vi.pdf](https://github.com/dh-hos/dhg.hospitalreports/files/9380888/So.XNTB.mau.ngoai.vi.pdf)
