### ISSUE TITLE
Lỗi - Xuất excel 3360: Form mẫu 80 (4210) và Form XML (4210) khác MA_LOAI_KCB

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#21]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **23/11/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_qdy_st_mau80`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2019046351` - _**MaKB**_: `2211013103` - _**MaBA**_: `2022005485` _**NgayKCB**_: `18/11/2022` - _**MaDV**_: `16` - _**ThangKT**_: `11` - _**NamKT**_: `2022`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
bệnh nhân nội trú có thời gian điều trị dưới 4h
Khi xuất xml và Excel form xuất XML 4210 thì trường ma_loai_kcb = 9
khi xuất excle form Mẫu 80 4210 thì trường ma_loai_kcb = 3
Bệnh viện gửi lên cổng bhxh không đối khớp được!

```
![image](https://user-images.githubusercontent.com/96155021/203452105-474ba943-d114-4ccb-b39a-f81c7c3276c2.png)

**Comment by vinh-dh** [comment]
[SetupHospitalReport20221123](https://www.fshare.vn/file/G7F8L148KS1J)

**Comment by le-an-87** [comment]
đã Fix!
