### ISSUE TITLE
Yêu cầu - Mở chức năng báo cáo chi tiết mẫu 26CT

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/dhg.hospitalreports#22]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn BI**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **02/12/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `74066`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Thị xã Tân Uyên**

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
https://github.com/dh-hos/dhg.hospitalreports/issues/3
```

**Comment by vinh-dh** [comment]
[SetupHospitalReport20221202](https://www.fshare.vn/file/ZSR42MN6NIAM)

**Comment by lqbinh1987** [comment]
Đã ok nhe anh @vinh-dh , anh @nghivanbi
