### ISSUE TITLE
Yêu cầu - Báo chi tiết mẫu 26ct theo nguồn.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalreports#23]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **05/12/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `74066`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Tân Uyên**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tanuyen_thu`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Yêu cầu bổ sung thêm chức năng xuất chi tiết thuốc, vtyt, xét nghiệm.......của nguồn chi phí BHYT, Thu Phí(Hình 1) giống như đã bổ sung bên nguồn Miễn phí(Hình 2)

Hình 1
![image](https://user-images.githubusercontent.com/99630883/205546566-b441d401-e8d8-4359-b69a-f854b957b2fe.png)

Hình 2
![image](https://user-images.githubusercontent.com/99630883/205546413-39788019-e4e4-46c9-be61-90d2fe524de2.png)

**Comment by vinh-dh** [comment]
Sử dụng trước cho đối tượng thu phí: [SetupHospitalReport20221207](https://www.fshare.vn/file/BYM1XDPAWGBY)

**Comment by lqbinh1987** [comment]
Cái mới bổ sung thêm cho nguồn thu phí nó hổng load lên đc tên Thuốc anh @vinh-dh ơi, VTYT cũng vậy lun.

![image](https://user-images.githubusercontent.com/99630883/206330309-3ee3c1c0-aeb0-42ac-b277-ab374486ad20.png)

**Comment by vinh-dh** [comment]
[SetupHospitalReport20221209](https://www.fshare.vn/file/VRZFSIWRSFFM)
