### ISSUE TITLE
Lỗi - Xem toa thuốc theo Bác Sĩ.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalreports#25]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **08/12/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92003`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Nhi Đồng CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_nhidong_gomtoa`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Trong cùng thời gian xem báo cáo, có 2 mã bệnh khác nhau, nhưng trùng họ và tên, mỗi BN có 1 toa thuốc, khi xem toa thuốc tổng hợp theo Bác sĩ thì trên from nó gom thành 1 BN và gom số dòng thuốc lại luôn.

![image](https://user-images.githubusercontent.com/99630883/206611322-46a2f484-cb44-4221-850f-67e09315b46e.png)
![image](https://user-images.githubusercontent.com/99630883/206611256-77d71e07-026b-4501-b182-2c2bcdacf677.png)

**Comment by vinh-dh** [comment]
Danh sách thuốc đó nó có 2 toa, phải chọn dòng thuốc đúng toa thì nó view đúng toa đó. Để anh bổ sung thêm cột Số HĐ trên danh sách thuốc để BV họ chọn. Vì chức năng view toa bên DLL [HospitalToaThuoc.dll](https://github.com/dh-hos/oLibraries/blob/main/HospitalToaThuoc.dll) nó hiển thị mỗi lần có 1  toa thôi.

**Comment by vinh-dh** [comment]
![image](https://user-images.githubusercontent.com/112069710/206619379-0977105c-c535-4e86-a2af-278303b99d30.png)


[SetupHospitalReport20221209v1](https://www.fshare.vn/file/JJS5ZB94J1A4)
