### ISSUE TITLE
Yêu cầu - Xuất excel cv 4811/BHXH

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalreports#27]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **05/01/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92003`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV NHi Đồng CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_nhidong_full`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Yêu cầu bổ sung dữ liệu cho cột GHICHU khi xuất excel theo CV 4811/BHXH lấy theo dữ liệu **bnnoitru.loidan**.
![image](https://user-images.githubusercontent.com/99630883/210923630-69472d46-8eb8-48c8-af42-38ddded40f13.png)

**Comment by vinh-dh** [comment]
Local:
- [SetupHospitalReport20230106](http://192.168.10.79:8090/Reports/SetupHospitalReport20230106.zip)

Fshare:
- [SetupHospitalReport20230106](https://www.fshare.vn/file/KF8KWLZU3MIH)
