### ISSUE TITLE
Lỗi - XML 2 tính sai tiền BHTT và BNTT

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#28]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **12/01/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92118`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Phụ Sản CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phusan_ct_bncct`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022105111` - _**MaKB**_: `2212014477` - _**MaBA**_: `017749` _**NgayKCB**_: `10/01/2023` - _**MaPhong**_: `45` - _**MaDV**_: `22` - _**ThangKT**_: `01` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**MaBYT**_: `40.30.457`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
XML 2 tính sai tiền BHTT và BNTT
- mã byt: 40.30.457 
- đơn giá: 575999.991
```
Cổng BHXH báo lỗi
![image](https://user-images.githubusercontent.com/96155021/211997774-baae8979-6cd6-4caa-823b-f7a0424c4076.png)
Reports xml2 mã byt 40.30.457 - đơn giá 575999.991
![image](https://user-images.githubusercontent.com/96155021/211998144-c3833a00-12a9-4802-930a-84553aadb609.png)
Tính lại theo công thức
![image](https://user-images.githubusercontent.com/96155021/211998398-05124f69-5fdc-4ff5-98b5-6f12b756ee0c.png)

**Comment by vinh-dh** [comment]
File Excel Bang2 anh xuất ra và tính lại vẫn là `345,599.98`

![image](https://user-images.githubusercontent.com/112069710/212003580-1a3f5db9-905c-4468-9dde-1d45caae32a7.png)

Anh không rõ là bệnh viện xuất ra và làm gì nữa?

**Comment by le-an-87** [comment]
anh tính thử cột BHTT thử cái anh! coi chừng sai từ đó

**Comment by vinh-dh** [comment]
> anh tính thử cột BHTT thử cái anh! coi chừng sai từ đó

À, rồi. Để anh coi lại chỗ cột này. Nhìn qua mấy cái hình tưởng báo cột t_bntt

**Comment by vinh-dh** [comment]
Local:
- [SetupHospitalReport20230113](http://192.168.10.79:8090/Reports/SetupHospitalReport20230113.zip)

Fshare:
- [SetupHospitalReport20230113](https://www.fshare.vn/file/GNN37GDAYTUJ)

**Comment by le-an-87** [comment]
đã fix!
