### ISSUE TITLE
Lỗi - XML và File Excel 3360 mẫu 80 cv 4210 xuất sai ma_loai_kcb bệnh nhân có thời gian điều trị 4h

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#29]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **18/01/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_lapvo_4h`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2019047572` - _**MaKB**_: `2301008341` - _**MaBA**_: `2023000482` _**NgayKCB**_: `17/01/2023 9:45:00 AM` - _**MaDV**_: `SA` - _**ThangKT**_: `01` - _**NamKT**_: `2023`
   > _**NgayVao**_: `17/01/2023 9:45:00 AM` - _**NgayRa**_: `17/01/2023 1:45:00 PM` 

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bệnh có thời gian điều trị = 4 giờ
1. XML xuất ma_loai_kcb = 3
2. File excel 3360 Mẫu 80 cv 4210 có ma_loai_kcb = 3
sai so với mô tả https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML4210/Hau-Mo-ta-XML-Noi-tru-4h-3788_BYT-BH.md
```
Mô tả 
![image](https://user-images.githubusercontent.com/96155021/213080658-4e28acbb-4a81-480a-b453-6570237faa4a.png)
XML
![image](https://user-images.githubusercontent.com/96155021/213080698-f4134275-4977-40d2-ae30-e25d615e4bc5.png)
xuất excel mẫu 80 4210
![image](https://user-images.githubusercontent.com/96155021/213080966-4c1a61b6-da65-487f-8a37-2ff4c4caf14e.png)

**Comment by vinh-dh** [comment]
Local:
- [SetupHospitalReport20230118](http://192.168.10.79:8090/Reports/SetupHospitalReport20230118.zip)

Fshare:
- [SetupHospitalReport20230118](https://www.fshare.vn/file/MCIALXLUBM1W)
