### ISSUE TITLE
Yêu cầu - Hỗ trợ xuất excel chi tiết Thuốc Mẫu 26a CT

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/dhg.hospitalreports#3]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn BI**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **29/08**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `ten_csdl`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
Thực hiện hỗ trợ như sau:
1. Bổ sung control để vào form xem chi tiết thuốc từ Form 26aCT
2. Hỗ trợ xuất excel dạng dữ liệu theo các cột của mẫu.

[mẫu PL4_NĐ29_Thuốc.xlsx](https://github.com/dh-hos/dhg.hospitalreports/files/9441323/m.u.PL4_ND29_Thu.c.xlsx)

```

**Comment by vinh-dh** [comment]
Cái này là chỉ áp dụng trên đối tượng miễn phí mẫu 26 BV Cù Lao Minh Bến Tre thôi phải không?

**Comment by nghivanbi** [comment]
- Áp dụng đối tượng miễn phí.
- Hiện chỉ cho CLM nhìn thấy control.

**Comment by vinh-dh** [comment]
@lqbinh1987 liên hệ BV lấy data về để có test nhe!

**Comment by vinh-dh** [comment]
@lqbinh1987 này làm riêng cho CLM, data đó đâu tác dụng.

**Comment by lqbinh1987** [comment]
Anh @vinh-dh .
À, em thấy nội dung yêu cầu có mục.
2. Hỗ trợ xuất excel dạng dữ liệu theo các cột của mẫu.
Nên e tưởng anh test này cho BV Mắt lun.

**Comment by vinh-dh** [comment]
[Reports 30/08/2022](http://www.fsend.vn/download/vpdyP2GAhDh2-CStdW1ApOwVtLt7WRf0)

![image](https://user-images.githubusercontent.com/112069710/187388400-1a1b2341-489c-4797-9a9c-78b1cf33f8eb.png)
![image](https://user-images.githubusercontent.com/112069710/187388441-5aa8180c-d2c3-4767-815a-1e5e58e544f6.png)

**Comment by nghivanbi** [comment]
Thực hiện lấy chi tiết cho các cột còn lại trên mẫu 26 tương tự thuốc.

**Comment by vinh-dh** [comment]
[Reports 09/09/2022](http://www.fsend.vn/download/I3gLaD6FGea1hr-IDG_p1tHqd_LPlaaZ)
