### ISSUE TITLE
Lỗi - BV 30/04: Thống kê bệnh nhân nội trú theo khoa trên Reports mới không thống kê theo tháng kế toán

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalreports#30]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **3/2/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94058`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV 30/04 Lao ST**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_laost_danhsachbn_sodongxml`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `31/01/2023` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `01, 02` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Thống kê danh sách bệnh nhân theo khoa trên Reports mới không thống kê theo ttháng kế toán khi có 1 ngày thuộc 2 khoa
- Ngày 31/01/2023 tháng kế toán 01/2023 và ngày 31/01/2023 tháng kế toán 02/2023
- Reports cũ: ngày 31/01/2023 có thống kê theo tháng kế toán

![ảnh](https://user-images.githubusercontent.com/97272332/216533897-369a9972-f1a0-4fca-a283-30a27cc139b1.png)
![ảnh](https://user-images.githubusercontent.com/97272332/216533928-67ad6596-9ed8-4c09-902b-b7a601363bb5.png)

- Reports mới: ngày 31/01/2023 của 2 tháng thống kê giống nhau
![ảnh](https://user-images.githubusercontent.com/97272332/216534193-6ba0c0a1-0722-4cec-adde-b927bd885b63.png)
![ảnh](https://user-images.githubusercontent.com/97272332/216534230-688bd38f-d8f1-4f54-acd7-c83eabc0a553.png)

**Comment by vinh-dh** [comment]
Đó là yêu cầu của nhiều BV nên bản mới theo ngày, không theo tháng kế toán. Vì theo tháng kế toán sẽ không thống kê được bệnh cũ.

**Comment by chauthanhtra** [comment]
Không thống kê được bệnh nhân cũ là sao vậy anh?

**Comment by vinh-dh** [comment]
Đang điều trị ==> Bệnh cũ đó.

**Comment by chauthanhtra** [comment]
BV báo không theo tháng kế toán khi báo cáo số lượng nhập xuất viện bị lệch, chiều ngày cuối tháng khoản 16h30 17h là cắt tháng rồi
nên các bệnh nhân nhập viện xuất viện chuyển viện sau đó phải báo cáo qua tháng sau
-> có cách nào cho tuỳ chọn theo ngày hay theo tháng không anh

**Comment by vinh-dh** [comment]
Không được. Theo cách cũ là bị sai, đó là lý do bản mới mới fix lại.
