### ISSUE TITLE
Lỗi - Kiểm tra thông tuyến báo lỗi

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#31]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **07/02/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `51008`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Nghĩa Hành**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_nghiahanh_reports_kttt`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023000196` - _**MaKB**_: `2302001392` - _**NgayKCB**_: `06/02/2023` - _**MaPhong**_: `16` - _**MaDV**_: `10` - _**ThangKT**_: `02` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Chức năng kiểm tra thông tuyến tại form xuất dữ liệu xml 4210 báo lỗi!

```
Kiểm tra tại Reports
![image](https://user-images.githubusercontent.com/96155021/217123024-e5c15817-3ed0-4917-a5ab-a2fe834225e9.png)
Kiểm tra tại Prescription
![image](https://user-images.githubusercontent.com/96155021/217123065-44c0ae11-8b7e-4901-81d9-63f7fdf3580d.png)

**Comment by vinh-dh** [comment]
![image](https://user-images.githubusercontent.com/112069710/217126436-f50028ce-bca9-439e-9ef3-dd6b9643f6e4.png)

@nghivanbi mày kiểm tra coi phiên bản đang sử dụng các dll là bản mấy? 

Reports hiện tại đang sử dụng:
- [OTH.XForms.dll](https://github.com/dh-hos/oLibraries/blob/main/OTH.XForms.dll) phiên bản: 1.22.1201.3
![image](https://user-images.githubusercontent.com/112069710/217126751-52e156f1-f416-4d6d-a148-8679665cd85d.png)

- [OTH.Entity.dll](https://github.com/dh-hos/oLibraries/blob/main/OTH.Entity.dll) phiên bản: 1.22.1201.6
![image](https://user-images.githubusercontent.com/112069710/217126769-306f47c1-3952-443e-bc31-9dd083a126e1.png)

**Comment by vinh-dh** [comment]
Local:
- [SetupHospitalReport20230207](http://192.168.10.79:8090/Reports/SetupHospitalReport20230207.zip)

Fshare:
- [SetupHospitalReport20230207](https://www.fshare.vn/file/4SD5FC9WIJVJ)

**Comment by le-an-87** [comment]
đã fix!
