### ISSUE TITLE
Lỗi - BC Danh sách thẻ tạm trang in không hiển thị giới tính

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#32]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **17/02/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_sadek_report`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023007665` - _**MaKB**_: `2302009983` - _**MaBA**_: `2023004901` _**NgayKCB**_: `17/02/2023` - _**MaPhong**_: `NHI_SS` - _**MaDV**_: `NHI` - _**ThangKT**_: `02` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
BC Danh sách thẻ tạm Trang in bị mất thông tin Giới tính, Ngày vào viện và ngày sinh hiển thị sai giờ
Form báo cáo không hiển thị hết các nút

```
Form báo cáo
![image](https://user-images.githubusercontent.com/96155021/219539141-acd9b743-87b2-413a-91b2-f74bf47041ea.png)
Trang in
![image](https://user-images.githubusercontent.com/96155021/219539257-8b2f0f4a-ebcd-43fa-9756-b6f16196e904.png)

**Comment by vinh-dh** [comment]
Local:
- [SetupHospitalReport20230217](http://192.168.10.79:8090/Reports/SetupHospitalReport20230217.zip)

Fshare:
- [SetupHospitalReport20230217](https://www.fshare.vn/file/552J8AEX816G)

**Comment by le-an-87** [comment]
![image](https://user-images.githubusercontent.com/96155021/219998120-c435ce53-f2c4-4b91-8a2f-535c9117e749.png)
trang in còn dính chổ ngày khám vào viện đó anh!

**Comment by vinh-dh** [comment]
Để a chuyển báo cáo này qua trang tự thiết kế. Để BV vào tự điều chỉnh luôn.

**Comment by le-an-87** [comment]
ok anh!

**Comment by vinh-dh** [comment]
Local:
- [SetupHospitalReport20230220](http://192.168.10.79:8090/Reports/SetupHospitalReport20230220.zip)

Fshare:
- [SetupHospitalReport20230220](https://www.fshare.vn/file/UUE7JT7BMWEX)

**Comment by le-an-87** [comment]
Đã bổ sung mẫu tự thiết kế!
![image](https://user-images.githubusercontent.com/96155021/220046263-fed834d6-295e-414c-9548-451d325f7e69.png)
