### ISSUE TITLE
Yêu cầu - Bổ sung tùy chọn trên sổ phẫu thuật, sổ thủ thuật

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/dhg.hospitalreports#33]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **21/02/2023**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20hoàn %20 thành-:-blue?style=plastic&logo=github) **24/02/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Bổ sung tùy cho phép người dùng chọn: 
- Phẫu thuật, thủ thuật không thanh BHYT.
- Phẫu thuật, thủ thuật thanh toán BHYT
- Tất cả

**Comment by vinh-dh** [comment]
Các BN ngoài đối tượng BHYT nó sẽ ảnh hưởng. Đề xuất: bổ sung thêm cột [Không BHYT] trên lưới thể hiện TT/PT không thanh toán, tương tự như [Yêu cầu - Bổ sung tiêu chí lấy báo cáo sổ chẩn đoán hình ảnh](https://github.com/dh-hos/dhg.hospitaldiagnose/issues/9)

**Comment by nghivanbi** [comment]
OK @vinh-dh

**Comment by vinh-dh** [comment]
Local:
- [SetupHospitalReport20230222](http://192.168.10.79:8090/Reports/SetupHospitalReport20230222.zip)

Fshare:
- [SetupHospitalReport20230222](https://www.fshare.vn/file/LFZH4WVHFFMI)
