### ISSUE TITLE
Lỗi - In BC chuyển tuyến tt40 báo lỗi

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#34]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **03/03/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phusan_ct_dutru_tutruc`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**ThangKT**_: `02` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Khi in bc chuyển tuyến TT40 phụ lục 2 và 3 báo lỗi!
```
![image](https://user-images.githubusercontent.com/96155021/222612558-4e242de4-7a57-44ed-b3f5-3c60ac8d8ac0.png)
![image](https://user-images.githubusercontent.com/96155021/222612864-a65e8c75-e865-441f-9832-27f40381167b.png)

**Comment by vinh-dh** [comment]
Local:
- [SetupHospitalReport20230303](http://192.168.10.79:8090/Reports/SetupHospitalReport20230303.zip)

Fshare:
- [SetupHospitalReport20230303](https://www.fshare.vn/file/6XZTWU8AG8HF)

**Comment by le-an-87** [comment]
Đã fix!
