### ISSUE TITLE
Lỗi - BC Mẫu 21 không load cls chuyển viện

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#35]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **03/03/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phongdien_mau21_cv`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2018001861` - _**MaKB**_: `2302002297` - _**MaBA**_: `2023000231` _**NgayKCB**_: `03/03/2023` - _**MaPhong**_: `N9` - _**MaDV**_: `04` - _**ThangKT**_: `02` - _**NamKT**_: `2023`
   > _**MaCLS**_: `CH266`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Mẫu 21 và 21 tổng hợp không load cls chuyển viện.
```
Mẫu 21 285 có cls chuyển viện
![image](https://user-images.githubusercontent.com/96155021/222658213-a42acc2c-69ab-4755-8f2f-1ebe7f45fdf7.png)
Mẫu 21 và 21 tổng hợp không có
![image](https://user-images.githubusercontent.com/96155021/222658282-3c4b452c-04a1-4065-b210-92f3d3b71635.png)
![image](https://user-images.githubusercontent.com/96155021/222658333-4dec2260-b717-49da-b237-40185da669cd.png)

cls chuyển viện
![image](https://user-images.githubusercontent.com/96155021/222658398-279984b7-b121-4a89-90bd-27164fbe7765.png)

**Comment by vinh-dh** [comment]
Đây không phải là lỗi, mà là do [Quyết định 1399/QĐ-BHXH](https://github.com/dh-hos/dhg.hospitalreports/files/10879437/1399_QD-BHXH.pdf) ngày 22/12/2014 có quy định chi tiết mẫu 21:
![image](https://user-images.githubusercontent.com/112069710/222664594-36849126-81fd-4f41-9b6f-774253708845.png)

Trên mẫu 21 theo quyết định này thì không đưa công khám lên đó. Để bệnh viện sử dụng đúng mẫu theo 1399 và thêm lựa chọn có đầy đủ CLS lên mẫu 21 theo quyết định này thì thời điểm đó Reports mở rộng giá trị tham số `rp.qd531`:
![image](https://user-images.githubusercontent.com/112069710/222664935-30c6a5a3-8e7f-4c11-b7f8-a72eb8a1f282.png)

Cụ thể, để sử dụng theo như đúng mẫu của 1399 thì `rp.qd531 = 5`, còn muốn thể hiện hết các CLS còn lại ngoài các CLS theo nhóm quy định ở mẫu đó thì `rp.qd531 = 6`.

Bệnh viện đang sử dụng `rp.qd531 = 5` nên không có chi phí chuyển viện lên mẫu 21 theo 1399 là đúng rồi.

**Comment by le-an-87** [comment]
ok anh!
