### ISSUE TITLE
Lỗi - 

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#36]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **10/03/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_dktp_toavtyt_tutruc`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023011638` - _**MaKB**_: `2303000001` - _**MaBA**_: `000001` _**NgayKCB**_: `09/03/2023` - _**MaPhong**_: `NLN08` - _**MaDV**_: `42` - _**ThangKT**_: `03` - _**NamKT**_: `2023`

   > _**KhoChan**_: `14` - _**KhoLe**_: `02` - _**MaHH**_: `AF45` - _**MaHH2**_: `TH272` - 

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
VTYT có áp trần thanh toán khi sử dụng tham số rp.dongia_xml = 1
XML Reports tính sai tiền BHTT, BNCCT và BNTT

```
Reports
![image](https://user-images.githubusercontent.com/96155021/224216001-cf02e994-a161-422d-9df2-6bde58e6856a.png)

Medicine áp giá bhyt
![image](https://user-images.githubusercontent.com/96155021/224216080-83eb2b3b-beb0-4dbb-9d1b-d1edaf78128b.png)

**Comment by vinh-dh** [comment]
Local:
- [SetupHospitalReport20230310](http://192.168.10.79:8090/Reports/SetupHospitalReport20230310.zip)

Fshare:
- [SetupHospitalReport20230310](https://www.fshare.vn/file/CQEI3KE2Q8PJ)

**Comment by le-an-87** [comment]
Đã fix!
