### ISSUE TITLE
Yêu cầu - Mẫu 21 CV 3762 - cột 9 thành tiền

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#38]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **15/03/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87005`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Lấp Vò ĐT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_lapvo_mau21_3762_tyle`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
BV đề nghị thay đổi cách tính cột 9 (Thành Tiền) biểu mẫu 21 CV 3762
- cột 9 (thành tiền) =  thành tiền đã tính tỷ lệ thanh toán.

lý do: BHXH hướng dẫn bệnh viện chỉnh lại thành tiền = thành tiền đã tính tỷ lệ thanh toán.

```
Mẫu 21 cv 3762
![image](https://user-images.githubusercontent.com/96155021/225225563-e4f19ef9-173e-4581-804e-f07dde7184e5.png)
XML 4210
![image](https://user-images.githubusercontent.com/96155021/225225753-2cfe0546-ec2f-4959-9065-ab8823f8d135.png)

**Comment by vinh-dh** [comment]
Có tham số này nè @le-an-87 
![image](https://user-images.githubusercontent.com/112069710/225263048-405fc744-b891-4db3-ad70-3e81a5042b21.png)

**Comment by le-an-87** [comment]
ok thanks anh!
