### ISSUE TITLE
Yêu cầu - STT mẫu 21 CV 3762

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#39]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **27/03/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92011`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Vĩnh Thạnh**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_vinhthanh_21_3762`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
BV yêu cầu mẫu 21 cv 3762 cột stt: ghi số thứ tự tăng dần theo từng nhóm.

```
![image](https://user-images.githubusercontent.com/96155021/227877222-4f997e11-0438-4a6f-a7db-3835e543b108.png)
![image](https://user-images.githubusercontent.com/96155021/227877315-8c01da85-faa5-4a30-87a1-06be74b99d35.png)

**Comment by vinh-dh** [comment]
Y/c này là chỉ dành riêng cho `92011` hay tất cả các BV @le-an-87 ?

**Comment by le-an-87** [comment]
chổ này hiện tại chỉ bệnh viện Vĩnh Thạnh yêu cầu thôi anh!

**Comment by vinh-dh** [comment]
Local:
- [SetupHospitalReport20230329](http://192.168.10.79:8090/Reports/SetupHospitalReport20230329.zip)

Fshare:
- [SetupHospitalReport20230329](https://www.fshare.vn/file/I5X25BSR6CUY)

**Comment by le-an-87** [comment]
đã cập nhật riêng cho bệnh viện 92011 !
