### ISSUE TITLE
Lỗi - Mẫu 80 theo 4210 - Excel CV3360_Cổng update 27/8/2019 - Lấy thông tin thẻ thứ 1

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitalreports#4]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ĐỨC**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **29/08/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94009`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **khach_hang**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_qdy_st`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**08**_: `ThangKT` - _**2022**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Mẫu 80 theo 4210 khi xuất Excel CV3360_Cổng update 27/8/2019 - tham số rp.excel_3360_02bhyt =0 là Lấy thông tin thẻ thứ 1.
**Nhưng lấy thông tin thẻ 2**

```
![image](https://user-images.githubusercontent.com/98437757/187141828-8bfea620-c704-4032-81d6-987e086e3b5b.png)

![image](https://user-images.githubusercontent.com/98437757/187141871-8793b194-47ca-469a-995b-13ec5bdf09b3.png)

**Comment by vinh-dh** [comment]
Cái này không phải lỗi, mà là cố tình làm như vậy. Xuất chỗ này là theo y/c của các đơn vị. Muốn xuất lấy thẻ còn hạn thì xuất 3360 ở XML4210 mới có.

**Comment by minhduc2it** [comment]
Xuất 3360 ở XML4210 tham số rp.excel_3360_02bhyt =0  thì không lấy thông tin thẻ 1 mà lấy Thông tin thẻ 2

**Comment by vinh-dh** [comment]
Thẻ 1 nè @minhduc2it 
![image](https://user-images.githubusercontent.com/112069710/187158011-6497af76-50f7-402b-9c27-0e6a3c24b6bb.png)

**Comment by vinh-dh** [comment]
Thử bản này nhé @minhduc2it [Reports 29/08/2022](http://www.fsend.vn/download/URk6xMch1MtMrBFRf2H1v3a6Sr0RwHGl)
