### ISSUE TITLE
Lỗi - XML tính sai tỷ lệ stent 2

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#40]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **30/03/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `89015`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tim Mạch AG**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_timmach_ag_stent2`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023001807` - _**MaKB**_: `2301013938` - _**MaBA**_: `2023000914` _**NgayKCB**_: `02/02/2023` - _**MaPhong**_: `E501` - _**MaDV**_: `06` - _**ThangKT**_: `02` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `03` - _**MaHH**_: `MSTT1103.15.02`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
XML Reports load sai tỷ lệ thanh toán VTYT Stent2 = 100%

```
XML
![image](https://user-images.githubusercontent.com/96155021/228705143-05efe35c-6fa3-4218-b1b3-baacaddc2374.png)
dm VTYT
![image](https://user-images.githubusercontent.com/96155021/228705207-a7116490-dbfa-4c2a-b2e0-555804a67ffb.png)

**Comment by vinh-dh** [comment]
Local:
- [SetupHospitalReport20230331](http://192.168.10.79:8090/Reports/SetupHospitalReport20230331.zip)

Fshare:
- [SetupHospitalReport20230331](https://www.fshare.vn/file/XDP7JVIMCJF7)

**Comment by le-an-87** [comment]
đã fix!
