### ISSUE TITLE
Lỗi - Mở form C79a-HD và C79a-HD (Theo QD 4210)

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalreports#44]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **07/04/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92003`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Nhi Đồng**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_nhidong_04_t3`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Khi mở form báo cáo  C79a-HD và C79a-HD (Theo QD 4210) thì xuất hiện lỗi như sau:

![image](https://user-images.githubusercontent.com/99630883/230532097-07cdd453-ec95-4df2-a8c5-a9c2daec01c6.png)

**Comment by minhduc2it** [comment]
Báo cáo Ngoại trú - Mẫu 25a mở from lỗi

![image](https://user-images.githubusercontent.com/98437757/230536421-13c81d48-4218-492c-bfbc-22756c596377.png)

**Comment by minhduc2it** [comment]
Báo cáo Quí năm > Ngoại trú > mẫu 79 và 25a-CT lỗi khi mở from

![image](https://user-images.githubusercontent.com/98437757/230552626-bd938f3a-ea93-4171-afd8-8321f902b00f.png)

**Comment by minhduc2it** [comment]
Báo cáo quí năm > Báo cáo tổng hợp > Mẫu 21 lỗi 

![image](https://user-images.githubusercontent.com/98437757/230555534-fd533a8a-15cc-47c9-8173-21e18155343d.png)

**Comment by vinh-dh** [comment]
Local:
- [SetupHospitalReport20230410](http://192.168.10.79:8090/Reports/SetupHospitalReport20230410.zip)

Fshare:
- [SetupHospitalReport20230410](https://www.fshare.vn/file/MTY37KWN8UF7)
