### ISSUE TITLE
Yêu cầu - Mở rộng chức năng khóa cố định cả ngày đối với nhân viên.

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/dhg.hospitalreports#45]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **14/04/2023**
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Khách hàng đã triển khai chức năng khóa theo giờ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `ten_csdl`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
![image](https://user-images.githubusercontent.com/91751241/231882148-c9f11736-7bc1-4eeb-bb26-3f1a7a0b722f.png)

```

**Comment by vinh-dh** [comment]
@le-an-87, @lqbinh1987 liên hệ PK Phương Nam lấy data để a test nhé!

**Comment by le-an-87** [comment]
em gửi tên data nhe anh: an_pkphuongnam_issues_45

**Comment by vinh-dh** [comment]
- Cập nhật cấu trúc:
![image](https://user-images.githubusercontent.com/112069710/232998966-2c3c0cce-f7a9-450f-8823-cd2696c87a91.png)

- [SetupHospitalReport20230419](https://gofile.me/78TQg/KOlBufNAt)

**Comment by nghivanbi** [comment]
![image](https://user-images.githubusercontent.com/91751241/233232683-e523d544-5fab-4e8c-9d97-b19a606d057c.png)
Lỗi thực hiện trên data: an_pkphuongnam_issues_45

**Comment by vinh-dh** [comment]
- [HospitalDiagnoseSetup20230420](https://gofile.me/78TQg/d8RQHTMaM)

**Comment by nghivanbi** [comment]
Trong quá trình thực hiện phát sinh trường hợp, **khóa khoảng thời gian theo ngày**. Ví dụ: T2 khóa khung giờ sáng, T3 khóa khung giờ chiều.... @vinh-dh cập nhật hỗ trợ nhé.

**Comment by vinh-dh** [comment]
- [SetupHospitalReport20230524](https://gofile.me/78TQg/zKwjrgez7)
- [HospitalDiagnoseSetup20230524](https://gofile.me/78TQg/PXY15oQc8)
- Cập nhật [DLL](https://github.com/dh-hos/oLibraries/commit/d3d03274f4c0148192503c7979fd309c7e9527f4) cho Pre.

**Comment by vinh-dh** [comment]
Lưu ý: Nhắc cơ sở chạy cập nhật cấu trúc trước khi sử dụng các module mới trên.

![image](https://github.com/dh-hos/dhg.hospitalreports/assets/112069710/e3939b66-b7e7-4898-b7e8-c7e1e143d407)

**Comment by vinh-dh** [comment]
- [SetupHospitalReport20230525](https://gofile.me/78TQg/Xs5xlUce6)
- [HospitalDiagnoseSetup20230525](https://gofile.me/78TQg/07V9WQrn7)
