### ISSUE TITLE
Yêu cầu - Thực hiện mô tả công văn 31/BHXH

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/dhg.hospitalreports#46]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **18/04/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `ALL`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**

```
[chi_tiet_yeu_cau](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML4210/20230415-Hau-CV1731-BHXH-G%C4%90%C4%90T-Thanh-toan-phau-thuat-vo-cam-gay-te.md)

```

**Comment by vinh-dh** [comment]
- [SetupHospitalReport20230428](https://gofile.me/78TQg/0BqyCEx6I)

**Comment by le-an-87** [comment]
Reports này chức năng gửi GCS, GBT và KSK anh để ở đâu vậy anh

**Comment by nghivanbi** [comment]
@le-an-87 test lại chức năng theo mô tả nhé

**Comment by le-an-87** [comment]
alo anh @vinh-dh ơi!
XML2 chưa được nhe anh!
thuốc này em cho chung toa vtyt kèm theo mà xml2 không ghép theo mô tả anh ơi
![image](https://user-images.githubusercontent.com/96155021/236367697-d1ac9982-e79a-46b7-ba6c-4cddbf3389fe.png)
![image](https://user-images.githubusercontent.com/96155021/236367833-2bcb3735-509b-4ee0-a2fb-e705a5e3f272.png)


XML3 thì ok rồi!
![image](https://user-images.githubusercontent.com/96155021/236367633-9936a4e3-782d-425b-b8fb-a9c23db48152.png)

**Comment by le-an-87** [comment]
Em gửi tên data để anh kiểm tra thử nhe
tên data: an_dean06_gcs_gbt_ksk
mã thuốc: AG14
thangkt: 04
namkt: 2023
Ngày kết thúc: 05/05/2023
mã bn: 2023009600
maba: 2023003838

**Comment by vinh-dh** [comment]
Ok, để a kiểm tra.

**Comment by vinh-dh** [comment]
- [SetupHospitalReport20230509](https://gofile.me/78TQg/ovl85u1gz)

**Comment by le-an-87** [comment]
Đã cập nhật theo đúng mô tả!

**Comment by nghivanbi** [comment]
Hiệu chỉnh theo mô tả cập nhật nhé: https://github.com/dh-hos/Mo-ta-he-thong/issues/24#issuecomment-1547187561

**Comment by vinh-dh** [comment]
- [SetupHospitalReport20230517](https://gofile.me/78TQg/LOn29s3Of)

**Comment by le-an-87** [comment]
đã bổ sung!

**Comment by ongtrieuhau** [comment]
Thực hiện lại theo [thay đổi ngày 13/06/2023](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML4210/20230415-Hau-CV1731-BHXH-G%C4%90%C4%90T-Thanh-toan-phau-thuat-vo-cam-gay-te.md) nhé a @vinh-dh

**Comment by vinh-dh** [comment]
- [SetupHospitalReport20230622](https://gofile.me/78TQg/PYcKUiVUx)

**Comment by le-an-87** [comment]
Đã bổ sung theo [mô tả ngày 13/06/2023](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML4210/20230415-Hau-CV1731-BHXH-G%C4%90%C4%90T-Thanh-toan-phau-thuat-vo-cam-gay-te.md)!
