### ISSUE TITLE
Lỗi - Mẫu 21 ngoại trú không load được danh sách bệnh nhân khi lick vào mã cls để xem chi tiết

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#48]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **19/04/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_tracu_042023_mau21_macls`

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `DI186` - _**PhieuYC**_: `Mẫu 21 ngoại trú`_**ThangKT**_: `04` - _**NamKT**_: `2023`_**HanBC**_: `từ ngày 11 đến 12`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Báo cáo mẫu 21 ngoại trú xuất từ ngày 11/4 đến 12/4
khi lick vào mã cls DI186 thì Reports không lấy đc danh sách bệnh nhân đã chỉ định

```
![image](https://user-images.githubusercontent.com/96155021/232962243-dd6f8d78-8a66-4c6e-a10b-78a9f940d4d9.png)
Danh sách trống
![image](https://user-images.githubusercontent.com/96155021/232962310-959cc8bf-5160-43ac-b491-659a63c707d2.png)

**Comment by vinh-dh** [comment]
Qua tuần a coi nhe. Anh đang ưu tiên công việc khác.

**Comment by vinh-dh** [comment]
- [SetupHospitalReport20230425](https://gofile.me/78TQg/br1zi4gtk)

**Comment by le-an-87** [comment]
đã fix!
