### ISSUE TITLE
Lỗi - XML2 tính sai tiền BHTT và BNTT

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#49]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **04/05/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_phusan_lechtien_xml_20230504`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023027056` - _**MaKB**_: `2304002748` - _**MaBA**_: `005563` _**NgayKCB**_: `02/05/2023` - _**MaPhong**_: `11` - _**MaDV**_: `40` - _**ThangKT**_: `05` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `14` - _**MaHH**_: `HU756` 

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
XML2 tính sai tiền BHTT và BNTT!

```
![image](https://user-images.githubusercontent.com/96155021/236140793-f78cde96-1e09-41bb-8e31-d866b3e0661c.png)

**Comment by vinh-dh** [comment]
Trường hợp này là do tham số rp.dongia_xml = 1, nên XML luôn lấy giá nhập kho làm đơn giá. Nhưng cột t_bhtt và t_bnccc là luôn đúng. Chỉ khác cột t_bntt là nó gánh thêm phần chi phí chênh lệnh.

**Comment by le-an-87** [comment]
ok anh!
