### ISSUE TITLE
Lỗi - XML 4210 và mẫu 80 lệch tiền giữa phiên bản mới và phiên bản củ

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#5]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87005`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Lấp Vò**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_lapvo_lech_report`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [``](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022009819` - _**MaKB**_: `2207014935` - _**MaBA**_: `2022005963` _**NgayKCB**_: `05/08/2022` - - _**MaDV**_: `01` - _**ThangKT**_: `08` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Lệch tiền XML 4210 và mẫu giữa phiên bản ngày 19/08/2022 và bản 27/06/2022!
Bảng kê 6556 cũng lệch giữa thành tiền bệnh viện và thành tiền bảo hiểm!

```
Lệch tiền XML 4210
![image](https://user-images.githubusercontent.com/96155021/187324325-19e6263e-aaab-4f6a-b9c3-5f9a34d95b48.png)
lệch tiền mẫu 80
![image](https://user-images.githubusercontent.com/96155021/187324353-b0dd2fd1-d731-4a1e-a02a-46fa4987be39.png)
Treatment 24/08/2022 Bảng kê 6556 thành tiền bệnh viện và thành tiền bh cũng lệch
![image](https://user-images.githubusercontent.com/96155021/187324414-e1004dd6-985a-4bc1-8a38-32f4477acafe.png)

**Comment by vinh-dh** [comment]
@le-an-87 Reports trước đó cách cấn trừ thuốc trả còn sai, ở bản mới fix lại cách tính mới đúng.

**Comment by le-an-87** [comment]
Hiện tại bệnh viện phàn nàn về vấn đề này đó anh!
dữ liệu đã gửi lên cổng bh và đã chốt số liệu rồi, đối soát khớp hết rồi, giờ cập nhật bản mới thì kiểm tra lại thì lệch.
cái này mình thống nhất lại cách cấn trừ lại cho khớp chứ lúc vầy lúc khác ảnh hưởng đến số liệu của bệnh viện mấy anh ơi!
anh @vuongdh ơi! kiểm tra lại giùm em chổ bảng kê luôn anh ơi!

**Comment by vinh-dh** [comment]
Cái cũ sai, cái mới fix đó @le-an-87. Còn muốn như cái cũ thì sử dụng cái cũ thôi (nhưng nó sai).
