### ISSUE TITLE
Lỗi - Báo cáo mẫu 21 nội trú thu phí - lệch số lượng giữa bản mới (28/04/2023) và bản củ (22/02/2023)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#50]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **08/05/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_yhct_ct_21thuphi`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `LA43` - _**PhieuYC**_: `Mẫu 21 nội trú - có phí` - _**ThangKT**_: `04` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Mẫu 21 nội trú có phí
Reports phiên bản ngày 28/04/2023 load không có thống kê mã cls LA43
lệch so với bản củ
Reports phiên bản ngày 22/02/2023 load thống kê mã cls LA43 có số lượng 717

```
bản 28/04/2023
![image](https://user-images.githubusercontent.com/96155021/236722336-0e80e102-fea2-4f1e-aa3c-3b5b1a5d123f.png)
Reports phiên bản ngày 22/02/2023
![image](https://user-images.githubusercontent.com/96155021/236722360-eb859f11-edc7-4a01-80f8-fe7c291386a1.png)

**Comment by vinh-dh** [comment]
Ok, để a kiểm tra.

**Comment by vinh-dh** [comment]
- [SetupHospitalReport20230511](https://gofile.me/78TQg/3baNDnRkf)

**Comment by le-an-87** [comment]
đã fix!
