### ISSUE TITLE
Lỗi - Định dạng số ký tự thập phân cột thành tiền mẫu 19, 20 xuất excel công văn 3131/BHXH-CSYT

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalreports#51]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **09/05/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `84006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Trà Cú**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_tracu_lechguitudong_rep`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2019004486` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `15/03/2023` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `03` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Lỗi khi gửi BHXH mẫu excel mẫu 19, 20 do định dạng cột thành tiền có 3 ký tự số thập phân (BV phải chỉnh tay lại để gửi BHXH)
BV Trà Cú đề nghị chỉnh lại định dạng số thập phân cột thành tiền mẫu excel 19, 20 công văn 3131/BHXH-CSYT thành 2 ký tự
(Hiện tại tất cả các mẫu excel 19, 20 công văn 3131 cột thành tiền đều lấy 3 ký tự số thập phân)

![ảnh](https://user-images.githubusercontent.com/97272332/236990834-797754c5-6089-47a1-ac94-637c61c3e176.png)
![ảnh](https://user-images.githubusercontent.com/97272332/236990876-40d1eed6-8eec-4991-9bf4-94db4ffabba0.png)

![ảnh](https://user-images.githubusercontent.com/97272332/237012492-fcdfebb3-69fc-4cac-a976-116efd5a9c5f.png)

**Comment by vinh-dh** [comment]
Ok, để a kiểm tra.

**Comment by vinh-dh** [comment]
- [SetupHospitalReport20230512](https://gofile.me/78TQg/cZCmRPPSq)

**Comment by chauthanhtra** [comment]
Alo anh @vinh-dh 
Mình có thể giữ cột số lượng và đơn giá là 3 ký tự số thập phân cho khớp với XML không anh
Chỉ chỉnh cột thành tiền thành 2 số thập phân 
Vì cổng BH hay bắt lỗi sai lệch giữa XML và mẫu tổng hợp

![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/97272332/fc746323-aee0-4722-877e-413fd83e34de)

**Comment by vinh-dh** [comment]
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/112069710/3296ee1c-31a8-4ffa-9827-72f7e9474d31)

Đã thực hiện theo 3131 thì làm sao có ngoại lệ? [CV 3131_BHXH-CSYT - Dinh dang du lieu mau 20, 21.pdf](https://github.com/dh-hos/dhg.hospitalreports/files/11476074/CV.3131_BHXH-CSYT.-.Dinh.dang.du.lieu.mau.20.21.pdf)

**Comment by chauthanhtra** [comment]
Vậy nó có lệch với XML4210 không anh?
Theo 4210 thì số lượng, đơn giá có 3 số thập phân, còn thành tiền thì lấy 2 số thập phân. mẫu cũ cổng BHXH chỉ báo lỗi cột thành tiền 
![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/97272332/07518619-092e-45b2-bbf5-65fd0211617f)

Hiện tại em không test được gửi mẫu này cổng BHXH được không? 

Phải chờ BV gửi dữ liệu mới biết nó có báo mẫu tổng hợp có khớp với XML không?

**Comment by chauthanhtra** [comment]
Để em gửi BV kiểm tra xem được không? hiện tại sợ không gửi lại được mẫu này.
