### ISSUE TITLE
Lỗi - Xuất excel mẫu 20 theo QĐ 917

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalreports#52]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **10/05/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Thạnh Trị**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_dbthanhtri_form_mamay`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `ALL` - _**MaKB**_: `ALL` - _**MaBA**_: `ALL` _**NgayKCB**_: `20/04/2023` - _**MaPhong**_: `ALL` - _**MaDV**_: `ALL` - _**ThangKT**_: `04` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Khi xuất Excel 917/QĐ-BHXH  **Mẫu 20 tổng hợp( theo 4210)** trên form xuất Dữ liệu tổng hợp 4210, thì cột **ten_hoatchat** lấy đúng tên hoạt chất, nhưng cột **ten_thuoc** cũng lấy tên hoạt chất -> sai, nhờ a Vinh sửa lại lấy đúng tên thuốc giúp em gấp, vì hiện tại BV đẩy lên cổng báo sai, nên không quyết toán được.

![image](https://github.com/dh-hos/dhg.hospitalreports/assets/99630883/8a9aed69-7aee-4eb4-b922-753eebda1bcf)
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/99630883/ceaecc4b-0dc3-4486-b04d-4fcda029d318)
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/99630883/599d7ea3-8396-40dc-9563-a309a9a3d099)

**Comment by vinh-dh** [comment]
Sai là do BV sai chứ không phải phần mềm sai. Xuất Excel là tên theo quy định của BYT, do đó khi kiểm tra em chịu khó kiểm tra thêm cột [Tên BYT]
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/112069710/2f1d6d80-0806-4ecf-8d07-a944e9f87b6f)
