### ISSUE TITLE
Yêu cầu - Bổ sung mẫu báo cáo Covid theo Nghị Định 29/2022/NĐ-CP

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalreports#53]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **09/05/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94058`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV 30/04 ST**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_laophoist`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Bổ sung các mẫu báo cáo theo [Nghị Định 29/2022/NĐ-CP](https://thuvienphapluat.vn/van-ban/The-thao-Y-te/Nghi-dinh-29-2022-ND-CP-huong-dan-Nghi-quyet-12-2021-UBTVQH15-511844.aspx) . 

Số liệu này toàn bộ là của nội trú, không có khám thường và BANT.
 
**Phụ lục II**: Chỉ lấy só liệu phần I.(Chi phí khám bệnh, chữa bệnh đối với người bệnh COVID-19 (bao gồm cả các bệnh khác kèm theo)

Cột 1: Tổng chi phí.
Cột 2: Tiền phát sinh cùng chi trả và BHYT không thanh của đối tượng BHYT, tiền phát sinh của đối tượng Thu phí.
Cột 3: Tiền BHYT thanh toán.
Cột 4: Để trống.
Cột 5: Tiền của các mặt hàng thuốc từ một số nguồn tài trợ khác.(có thể tận dụng Check nguồn tài trợ trên dm thuốc, nhưng để đảm bảo dữ liệu BV đang chạy thì e đề nghị bổ sung Check giống như a Vinh nói, để xác định thuốc đó để đưa số liệu vào cột này)
Cột 6: = cột 1
Cột 7: Để trống

**Phụ lục III**: Chỉ lấy số liệu cho mục I, II, III, IV, số liệu các cột thì như **Phụ lục II** ở trên.

**Phụ lục IV**: Lấy chi tiết nhóm theo từng BN, ví dụ như hình.
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/99630883/3a91b224-7917-4333-8cf8-ae002cacf860)

**Comment by nghivanbi** [comment]
Đã báo giá và thống nhất với bệnh viện, tiến hành thực hiện nhé!

**Comment by vinh-dh** [comment]
Phụ lục 2:

Cột 6 = Cột 1
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/112069710/33ba0197-ba26-4156-88f2-f6b2af04435e)

Nhưng mẫu thì Cột 1 = 2 + 3 + 4 + 5 + 6
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/112069710/07f7de4f-1b91-4ef3-9720-4e988e211438)

Thấy sai sai!

**Comment by lqbinh1987** [comment]
Anh @vinh-dh .

**Phụ lục 2 và 3.**

- **Thuốc:**

Cột 1: Tổng chi phí, cột 2+3+4+5+6.
Cột 2: Tiền thuốc của nguồn ngân sách, có mã thuốc bắt đầu 2 ký tự là 'CV' và những mã 'O69','O70','O71','O72'.(Những thuốc này không check BHYT trong danh mục thuốc)
Cột 3: Tiền thuốc BHYT thanh toán.
Cột 4: Để trống.
Cột 5: Tiền thuốc của các mặt hàng từ một số nguồn tài trợ khác, có mã thuốc bắt đầu 2 ký tự là 'TT','UT'.(Những thuốc này không check BHYT trong danh mục thuốc).
Cột 6: Tiền thuốc phát sinh cùng chi trả với BHYT, và tiền thuốc còn lại của tất cả mã thuốc khác ngoài các mã trong cột 2 và cột 5.
Cột 7: Để trống
Cột 8: Để trống

- **DVKT:**
Cột 1: Cột 5 + Cột 6
Cột 2, 3, 4: Trống.
Cột 5: Tiền tất cả DVKT miễn phí(xác định miễn phí trong danh mục cls)
Cột 6: Tiền còn lại tất cả DVKT khác, lấy theo nguồn chi phí của BN: đối tượng thuộc loại thu phí (06, 10), đối tượng thuốc loại BHYT(01, 09) nhưng chỉ định không bhyt(chidinhcls.bhyt=0).

**Phục lục 4**:
Cột 4: Bổ sung thêm giá trị từ ghi chú trong danh mục thuốc(**dmthuoc.ghichu**)

**Comment by vinh-dh** [comment]
Anh cần xác nhận lại cách ghi nhận đổi với DVKT:
- Cột 5: lấy chi phí dựa vào cột `dmcls.mienphi` chứ không phải dựa vào đối tượng và các cột `chidnhcls.miengiam` và `chidnhcls.ptmiengiam` phải không?
- Cột 6: chi phí tại cột này là đã loại trừ chi phí của cột 5 phải không?

Xác nhận 2 câu hỏi trên để anh tiếp tục thiết kế!

**Comment by lqbinh1987** [comment]
Dạ ok anh @vinh-dh .

**Comment by lqbinh1987** [comment]
Số liệu đã lấy cơ bản ok, nhưng nhờ a @vinh-dh  bổ sung loại báo cáo, cho chọn Từ ngày....Đến ngày....., để BV tự chọn thời gian báo cáo. Vì hiện tại cho chọn theo quý, năm, người dùng phải cộng lại từng khớp mất thời gian.

**Comment by vinh-dh** [comment]
Dữ liệu phần mềm khi truy vấn phải có tháng và năm. Không có (chỉ có điều kiện ngày) thì sẽ cực kỳ chậm (do cấu trúc dữ liệu của phần mềm luôn có index theo tháng và năm). Đồng ý bỏ tháng và năm chỉ lấy theo điều kiện từ ngày đến ngày xác nhận thì anh thay đổi chỗ đó.

**Comment by lqbinh1987** [comment]
Dạ e xác nhận bổ sung hoặc đổ dùm em nhe anh.

**Comment by lqbinh1987** [comment]
Với nhờ a @vinh-dh bổ sung thêm dùm em lọc thêm Mã BN như bên báo cáo 4210, mục đích để lấy thêm 1 số BN nằm rải rác ở các khoảng thời gian.

**Comment by vinh-dh** [comment]
Ok

**Comment by lqbinh1987** [comment]
Gáng tranh thủ dùm em nhe a @vinh-dh, BV nó đang cần gấp.
