### ISSUE TITLE
Yêu cầu - Đơn giá mẫu 21 xuất theo Quyết Định 917/QĐ-BHXH.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalreports#54]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **10/05/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `ALL`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **ALL**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `dbthanhtri_112023`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Do hiện tại Cổng tiếp nhận đang yêu cầu các đơn vị gửi hồ sơ tổng hợp mẫu 19 20 21 theo QĐ 917/QĐ-BHXH, trong đó mẫu 21 trên phần mềm mình đang lấy **đơn giá sau khi tính tỷ lệ** thanh toán(hình 1) đối với các trường hợp công khám lần 1, 2, 3..., TT/PT lần 2, tiền giường bệnh nằm ghép.
Nhưng hiện tại cổng đang đối chiếu mẫu 21 Excel phần mềm mình gửi lên không khớp với chi tiết XML cũng gửi từ PM lên cổng.
Cổng yêu cầu, nếu cũng 1 mã dịch vụ mà có 2 dòng đơn giá khác nhau do có tính tỷ lệ thanh toán, thì phải **gom lại 1 dòng** và cột đơn giá phải thể hiện đơn giá trước khi tính tỉ lệ thanh toán(giá phê duyệt), nhưng thành tiền phải tính theo đơn giá sau khi tính tỷ lệ thanh toán. Ví dụ cụ thể như hình dưới.
_Tất cả các khách hàng đều bị bắt trường hợp này, và cổng bắt vậy, không có văn bản_

![image](https://github.com/dh-hos/dhg.hospitalreports/assets/99630883/71a0abe9-ee8e-4a71-b859-40e18b002866)
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/99630883/8ab8a712-ddad-4f46-acee-ede404f19bca)

**Comment by lqbinh1987** [comment]
Anh @nghivanbi và anh @vinh-dh xem xét yêu cầu này dùm em.

**Comment by lqbinh1987** [comment]
> Anh @nghivanbi và anh @vinh-dh xem xét yêu cầu này dùm em.

Nhờ a @nghivanbi xem dùm em chổ yêu cầu này.

**Comment by nghivanbi** [comment]
Này vướng gì không @vinh-dh ?

**Comment by vinh-dh** [comment]
@lqbinh1987 quy đổi thì tính lại số lượng nhe, khi đó nó mới khớp thành tiền. Có chấp nhận khi số lượng bị thay đổi hay không?

**Comment by lqbinh1987** [comment]
Anh @vinh-dh , cái này đâu ảnh hưởng bởi số lượng anh, này lấy đơn giá mà anh.
Như hình ví dụ ở trên, phần mềm mình đang tách 2 dòng đơn giá: dòng giá nguyên giá, dòng giá theo tỷ lệ.
Nhưng cổng nó yêu cầu gom lại 1 dòng, số lượng là số lượng tổng gom lại, giá thì là giá nguyên giá, **còn thành tiền phải thì phải tổng tiền của Số lượng x đơn giá của mỗi dòng theo tỷ lệ và nguyên giá cộng lại.**

![image](https://github.com/dh-hos/dhg.hospitalreports/assets/99630883/cdbbe350-f8f5-4dfb-b1cb-f4d55d4f29f7)

**Comment by vinh-dh** [comment]
Sao mà không ảnh hưởng? 6556 và XML thì có cột tỷ lệ, nên nhân giữa số lượng và đơn giá có nhân thêm tỷ lệ. Còn mẫu 21 (cũ, mẫu này có trước XML và 6556) nó lại không có cột tỷ lệ. Em kêu lấy đúng giá và đúng số lượng (mà nó không có cột tỷ lệ) thì nó lệch với thành tiền thì lúc đó làm sao?

**Comment by vinh-dh** [comment]
Lúc đó, như cái ví dụ hình của em:
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/112069710/1bc2876f-298f-48ca-91d8-6debc1ad8f18)

Nó đem nhân lại như thế này, rồi nó nói làm sai nữa thì sao?
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/112069710/25d48199-4193-47da-9610-4fc55c2272c2)

**Comment by nghivanbi** [comment]
- Cái đó nếu group số lượng và tiền theo bệnh nhân làm được không?

**Comment by vinh-dh** [comment]
Mục đích để làm gì? Hiện tại theo công văn sao không theo?

**Comment by nghivanbi** [comment]
@lqbinh1987 nhờ các bệnh viện làm giấy yêu cầu nhé, rồi anh quyết, ghi cụ thể nội dung như yêu cầu em để có cơ sở nhé!

**Comment by lqbinh1987** [comment]
Cái này do cổng nó lấy tự động ra từ xml mình gửi lên rồi đối chiếu với excel mình gửi lên, các BV hiện đều xuất ra rồi phải chỉnh tay file excel lại rồi gửi lên cổng nó mới chấp nhận, hiện chưa có công văn nhưng cổng nó đối chiếu tự động.

**Comment by lqbinh1987** [comment]
Có yêu cầu của Khách Hàng gửi về nhe a @nghivanbi 
[BB YÊU CẦU.pdf](https://github.com/dh-hos/dhg.hospitalreports/files/11977155/BB.YEU.C.U.pdf)

**Comment by lqbinh1987** [comment]
Anh @nghivanbi

**Comment by nghivanbi** [comment]
@vinh-dh bổ sung 1 option cho phép các đơn vị xuất như sau:
+ Đơn giá: không tính tỉ lệ
+ Số lượng: sum số lượng
+ Thành tiền: sum thanh tiền
--> chấp nhận thành tiền # số lượng * đơn giá.

**Comment by vinh-dh** [comment]
- File: [SetupHospitalReport20231228.zip](https://gofile.me/78TQg/9ZlS3PeMl)
