### ISSUE TITLE
Lỗi - in mẫu 21 theo 285 tại báo cáo mẫu 79 4210

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#58]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **01/06/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_giarai_79_linkbangke`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/18fURx8SZ)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2019032419` - _**MaKB**_: `2306000276` - _**MaBA**_: `N2023003195` _**NgayKCB**_: `01/06/2023` - _**MaPhong**_: `03` - _**MaDV**_: `10` - _**ThangKT**_: `06` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Khi thực hiện in mẫu 21 theo cv 285 tại form báo cáo mẫu 79 4210 báo lỗi ( bệnh ngoại trú và bệnh án ngoại trú)

```
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/cf5ef2d0-3f38-4fc8-ba9f-a89deda4ffab)

**Comment by vinh-dh** [comment]
- [SetupHospitalReport20230602](https://gofile.me/78TQg/Jb5PopsUt)

**Comment by le-an-87** [comment]
Đã fix!
