### ISSUE TITLE
Lỗi - MẪU 80 VÀ 4210 LẤY THIẾU CHI PHÍ VTYT

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hospitalreports#60]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HÒA**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **02/06/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92003`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BỆNH VIỆN NHI ĐỒNG CẦN THƠ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_dbnhidong2023014257_lechchiphi01_report`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `05` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `VT22_118` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Chi phí tại Bảng kê phiếu 01 có liệt kê nhưng mẫu 80 và 4210 thiếu 1 vật tư 
VT22_118-Bộ dụng cụ thả dù Occlutech Delivery Set (ODS) các loại, các kích cỡ.

![image](https://github.com/dh-hos/dhg.hospitalreports/assets/130281806/074817e0-cddc-4833-b9ba-6bc41b30cdf0)
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/130281806/467dbb73-1719-4a87-bfb5-83da5d75472a)
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/130281806/af124b49-4f67-4000-8bdd-fd3107f46dc3)

**Comment by vinh-dh** [comment]
Qua tuần a coi nhe.

**Comment by vinh-dh** [comment]
Số hóa đơn: `C6.V23.0531.153504`, cột ngaylap bị lệch ở 2 table, xml nó không load được là phải rồi.

- chungtu: `ngaylap = 25/05/2023`
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/112069710/2179bf4a-71c3-41f5-ae97-cabb5a8d2637)

- pshdxn: `ngaylap = 26/05/2023`
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/112069710/6078551f-0977-43b4-a333-ebfdef5dc1aa)
