### ISSUE TITLE
Lỗi - Thiếu mã giường trên XML3

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalreports#61]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Vương**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **5/6/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92013`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV YHCT CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `vuong_yhct_ct_thieumagiuong`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/B5ibqNTzI)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023008890` - _**MaKB**_: `MaKB` - _**MaBA**_: `2023001630` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `06` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `NG26` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Thiếu mã giường trên XML3  
- Mất diễn biến chỉ định CLS mã NG26 trong quá trình điều trị (iddienbien = D19.20230524.102816)
-
![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/97272332/a4894ebc-5f10-4aac-b337-0aa9be5fd2cd)

**Comment by vinh-dh** [comment]
Xong các các công việc ưu tiên a coi.

**Comment by vinh-dh** [comment]
Ủa, cột `ma_giuong` trong `chidinhcls` đang rỗng nè @vuongdh, @chauthanhtra:

![image](https://github.com/dh-hos/dhg.hospitalreports/assets/112069710/3444540b-d59b-4fef-bc9b-1931e12f9783)

**Comment by vuongdh** [comment]
@chauthanhtra đã hỗ trợ BV (đã upload script)--> do diễn biến trong qtdieutri bị xóa

**Comment by chauthanhtra** [comment]
close issue này nha anh @vuongdh

**Comment by vuongdh** [comment]
@chauthanhtra em lập kịch bản test dùm anh: phải từ 2 máy mới test được.
Bước 1: máy 1: chọn diễn biến mới và vô chỉ định CLS (chưa cho cls)
Bước 2: máy 2 chọn diễn biến mà máy 1 đã chọn rồi xóa đi
Bước 3: máy 1 tiếp tục cho cls --> xem có lưu được cls hay không?

**Comment by vuongdh** [comment]
@chauthanhtra Close được rồi em
