### ISSUE TITLE
Lỗi - Xem và in mẫu Báo cáo quân nhân QN-01/BHYT

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalreports#62]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **8/6/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94009`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Quân Dân Y ST**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_qdy_st_reports_baocaoquannhan`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/9ixxaJjmo)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `06` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

- Phần mềm Reports báo lỗi khi chọn chức năng Báo cáo Quân nhân QN-01/BHYT (Báo cáo tổng hợp và báo cáo quí - năm), bấm Continue thì vẫn vào được báo cáo
- Khi bấm in Báo cáo Quân nhân QN-01/BHYT trong báo cáo quí-năm thì không in được

![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/97272332/211f4c54-05a8-43ea-9cf5-e8fc743fc710)
![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/97272332/83a7af74-5ea4-4f94-b4f8-17ff172fce08)
![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/97272332/b8d0904f-2fd4-4b57-b746-003e42223fc0)

**Comment by vinh-dh** [comment]
Đang ưu tiên các công việc gấp khác. Qua tuần anh coi.

**Comment by chauthanhtra** [comment]
Ok anh

**Comment by vinh-dh** [comment]
- [SetupHospitalReport20230616](https://gofile.me/78TQg/Tbl8aTkE8)
