### ISSUE TITLE
Lỗi - Report Lỗi báo cáo 26a, 80a

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitalreports#64]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Đức**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **13/06/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92085`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tâm Thần Cần Thơ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_tamthan_26a`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022005741` - _**MaKB**_: `2305002844` - _**MaBA**_: `2023000459` _**NgayKCB**_: `22/05/2023`  _**ThangKT**_: `05` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bệnh nhân tổng tiền chưa vượt mức 15% Lương cơ bản

```
Mẫu 26a và 80a tính % thu khi mức hưởng trên phiếu 01 là 100%
Mẫu 80a theo 4210 và XML 4210 lấy đúng 

![image](https://github.com/dh-hos/dhg.hospitalreports/assets/98437757/e6b30ab0-f289-4550-aaa8-0df6fcaf9be2)

![image](https://github.com/dh-hos/dhg.hospitalreports/assets/98437757/38b09d29-63db-4fd8-be4b-f1b155668577)

**Comment by vinh-dh** [comment]
Anh xử các công việc ưu tiên trước đó xong sẽ coi.

**Comment by minhduc2it** [comment]
đã giải thích bv
