### ISSUE TITLE
Yêu cầu - Sổ Lưu trữ bệnh án ngoại trú thêm cột khoa xuất viện

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalreports#65]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **13/06/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77114`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Phòng khám đa khoa Bình An**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbbinhancs2`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

Phòng khám muốn Sổ lưu trữ BA Ngoại trú hiển thị thêm khoa xuất viện như hình dưới 
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/97272364/80add061-c57f-4d05-9080-fc09170aa978)

**Comment by vinh-dh** [comment]
Ok, để a kiểm tra lại code.

**Comment by vinh-dh** [comment]
- [SetupHospitalReport20230615](https://gofile.me/78TQg/NNC7spDmk)
