### ISSUE TITLE
Lỗi - Báo cáo Cận lâm sàng chi tiết không check đã thực hiện các CLS PT-TT thu phí chưa thu tiền

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalreports#67]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **19/6/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92007`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Ô Môn**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_omon_bccanlamsang`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/iwbkfXVjk)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023017450` - _**MaKB**_: `MaKB` - _**MaBA**_: `2023005809` _**NgayKCB**_: `4/5/2023` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `03` - _**ThangKT**_: `05` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `TH1060` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Reports -> Báo cáo tổng hợp -> báo cáo cận lâm sàng -> xem chi tiết CLS mã TH1060

CLS đã lập phiếu PT-TT nhưng lên báo cáo cận lâm sàng vào xem chi tiết CLS vẫn không check Đã thực hiện
(Em kiểm tra thấy các CLS PT-TT thuộc đối tượng thu phí chưa thu tiền sẽ không check đã thực hiện. Em check đã thu trên dữ liệu thì Reports sẽ đánh dấu đã thu và đã thực hiện)

![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/97272332/52ddda65-f7df-43a2-9407-14c9ed95439b)
![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/97272332/e77b33b1-22e5-4ab0-bb2c-f52faced7cf5)
![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/97272332/01cbe4d0-19ef-4b76-89ea-e686ea261579)

**Comment by vinh-dh** [comment]
Ok, để a kiểm tra.

**Comment by vinh-dh** [comment]
- [SetupHospitalReport20230621](https://gofile.me/78TQg/yiZxdEyaM)
