### ISSUE TITLE
Lỗi - BCTH xác định sai bệnh nhân nội tỉnh đến

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#68]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **20/06/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_cairang_bcth`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/Du5oDZ2Bn)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023002043` - _**MaKB**_: `2306006149` - _**NgayKCB**_: `19/06/2023` - _**MaPhong**_: `46` - _**MaDV**_: `04` - _**ThangKT**_: `06` - _**NamKT**_: `2023` - _**mabvdk**_: `92006` - _**MaThe**_: `DN4927510159346`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
BCTH ngoại trú thẻ đăng ký tại bv nhưng bc đưa qua mục C thẻ ngoại tỉnh đến.

```
Mẫu 79 nội tỉnh
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/5d55f16a-ef06-4799-9410-eeed36a48a74)
BCTH ngoại tỉnh
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/29388197-bf70-4324-bcef-82be2dea53db)

**Comment by vinh-dh** [comment]
Ok, để anh kiểm tra.

**Comment by vinh-dh** [comment]
- [SetupHospitalReport20230623](https://gofile.me/78TQg/6HW6HEd93)

**Comment by le-an-87** [comment]
Đã fix!
