### ISSUE TITLE
Lỗi - Mẫu 19, 20, 21 in theo CV 1399 và mẫu 21 CV 285 không hiển thị ngày báo cáo dưới tiêu đề

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalreports#69]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **3/7/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_cairang_giayrv_bant`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/JDVpohBrN)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**07**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Reports mới 
Mẫu 19, 20, 21 in thường và in theo công văn 1399 và mẫu 21 in theo CV 285 không hiển thời gian báo cáo

![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/97272332/2a713618-ab5d-4af7-8846-816189147c08)
![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/97272332/b539fadd-99c2-40a9-812e-75ee16eeb027)

![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/97272332/caf6d622-a2f3-4fa2-b17a-3130d04cac0f)
![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/97272332/0ce2eae6-2bbe-438a-a55a-34d479d9471b)

**Comment by vinh-dh** [comment]
Để a kiểm tra.

**Comment by vinh-dh** [comment]
- [SetupHospitalReport20230705](https://gofile.me/78TQg/0JhBZ7JXH)

**Comment by chauthanhtra** [comment]
Alo anh @vinh-dh 
Chổ thời gian báo cáo Quí mình ghi dạng : Quí .... năm .... như được không anh ví dụ: Quý III năm 2023 (hiện tại ghi: Báo cáo quý 3/2023 nhìn giống tháng 3/2023)

![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/97272332/22c821f0-bee0-4b90-a950-979ba70add89)

**Comment by vinh-dh** [comment]
- [SetupHospitalReport20230707](https://gofile.me/78TQg/MyFQWT1Rt)
