### ISSUE TITLE
Lỗi - Bệnh nhân đã in phiếu thanh toán 6556 rồi nhưng Reports không xuất được dữ liệu

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#7]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **09/09/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `74066`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tân Uyên**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_tanuyen_2208008287_report`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022025134` - _**MaKB**_: `2208008287` - _**NgayKCB**_: `29/08/2022` - _**MaPhong**_: `M01` - _**MaDV**_: `YTCD` - _**ThangKT**_: `08` - _**NamKT**_: `2022`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bệnh nhân khám đối tượng bhyt và có chi phí thanh toán bảo hiểm
Đã in phiếu 01 rồi nhưng Reports vẫn không load được bệnh nhân này

```
Printer đã in bệnh nhân
![image](https://user-images.githubusercontent.com/96155021/189256841-24cfb8d1-a4a0-4d26-96bf-9ae798965323.png)
![image](https://user-images.githubusercontent.com/96155021/189257241-ea31c803-15e4-48e5-9fd5-58ece7c7826e.png)

Reports xuất dữ liệu không có bệnh nhân
![image](https://user-images.githubusercontent.com/96155021/189257420-2e37b597-d6f2-4a06-8055-185670d6e26a.png)

**Comment by vinh-dh** [comment]
Cấu hình khoa khám bệnh nhân này chưa phù hợp nè @le-an-87. Chọn loại là khoa/khoa ngoại/khoa nội đi.
![image](https://user-images.githubusercontent.com/112069710/189261152-b4e4928f-0774-4c71-b269-916036bbc950.png)

**Comment by le-an-87** [comment]
ok thanks anh!
để em hướng dẫn bv.
