### ISSUE TITLE
Lỗi - Mẫu 79 cv 102 tổng các cột thống kê chi phí lệch so với cột tổng tiền

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#70]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **11/07/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_hongngu_79_102`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/OuDMjEl87)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022015138` - _**MaKB**_: `2306013011` - _**MaBA**_: `2023010230` _**NgayKCB**_: `04/07/2023` - _**MaDV**_: `03` - _**ThangKT**_: `07` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Mẫu 79 cv102 khi cộng tất cả chi phí trong group theo nhóm chi phí lệch tiền so với cột Tổng cộng 

```
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/40580e24-9289-41d3-9d07-4ac6c697984f)

**Comment by vinh-dh** [comment]
Ok, để a kiểm tra.

**Comment by vinh-dh** [comment]
- [SetupHospitalReport20230712](https://gofile.me/78TQg/0Zxv2oI3l)

**Comment by le-an-87** [comment]
đã fix!
