### ISSUE TITLE
Lỗi - Mẫu 26 TH tháng và quí lấy số lượng bệnh không khớp với mẫu 26CT

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#71]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **12/07/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_qdy_st_12_01_2023`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/ot6gwPbht)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaDV**_: `05` - _**ThangKT**_: `01` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Báo cáo mẫu 26 TH, 26TH (4210) và 26 TH quí khi xuất dữ liệu thu phí tháng 01/2023 thu phí lệch số lượng bệnh so với mẫu 26 CT
-> Kiểm tra 1 số bệnh theo mẫu ct đều thuộc khoa 05 và đối tượng 06

```
Mẫu 26 CT tổng 14 lượt
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/813885ad-da6c-4a8e-84fc-a0209a361999)

Mẫu 26 TH
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/e05df50e-b494-4b6a-808e-8941f2bef37e)
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/d62ec8d1-ea21-459d-ad19-b62b7ea8a772)
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/bd1ab9b0-6eef-4cf0-9a49-c8f2f63e8687)

**Comment by vinh-dh** [comment]
Ok, để anh kiểm tra.

**Comment by vinh-dh** [comment]
- [SetupHospitalReport20230719](https://gofile.me/78TQg/HBe7mYseb)

**Comment by le-an-87** [comment]
Đã fix!
