### ISSUE TITLE
Lỗi - Sai mẫu in 25a-CT

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalreports#73]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **1/8/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92080`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TYT Giai Xuân**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_qdy_st_full_treat_tutat`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `18/07/2023` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `07` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Khi bấm in mẫu 25a-CT (Báo cáo tổng hợp, báo cáo Quí năm) thì phần mềm in mẫu C79-HD

![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/97272332/863f43d3-9369-48a6-a7ec-1bbe28c0d4e8)
![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/97272332/9c553428-aba6-493e-bc05-51fbb1a32046)

**Comment by vinh-dh** [comment]
Ok, để anh kiểm tra.

**Comment by vinh-dh** [comment]
- [SetupHospitalReport20230804](https://gofile.me/78TQg/f4jlJFuAr)

**Comment by chauthanhtra** [comment]
Alo anh @vinh-dh 

Anh kiểm tra lại giúp em mẫu 25a-CT  in theo nhóm (báo cáo tổng hợp, báo cáo quí năm) bị sai
![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/97272332/e7d731a2-e154-4955-aff1-76f8285ef84b)
![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/97272332/7a6899b7-38bd-46d9-918e-4cda758736c0)
![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/97272332/32933f79-9603-4ce3-9ec8-538bf46497ba)

**Comment by vinh-dh** [comment]
Ok, để anh kiểm tra lại.
