### ISSUE TITLE
Lỗi - In toa thuốc báo lỗi

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitalreports#74]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Đức**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **07/08/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77025`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PK Đông Tây**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_dongtay_intoa`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/nwBe7dOMJ

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**NgayKCB**_: `06/08/2023` - _**ThangKT**_: `08` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Ngoại trú > In toa thuốc > Bấm in báo lỗi

```
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/98437757/fc13bfa2-f782-43cb-86c0-18d7f6a73a96)

![image](https://github.com/dh-hos/dhg.hospitalreports/assets/98437757/3916f90a-3684-4ed9-80fb-00977e1df69f)

**Comment by vinh-dh** [comment]
Ok, để anh kiểm tra.

**Comment by vinh-dh** [comment]
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/112069710/1b5defd1-ce03-4b5f-8f15-5bc64c1f2979)

@nghivanbi Reports đang sử dụng thư viện [HosReg.Code.dll](https://github.com/dh-hos/oLibraries/blob/main/HosReg.Code.dll) phiên bản: `3.23.724.5`
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/112069710/ee0e1c73-a892-4676-bbb1-a8e254d6f699)

Khi in từ form `HosReg.Code.Forms.FrmInToa` lỗi:
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/112069710/dc4ddf69-5f47-4eaa-a700-79626b1b7f2c)

Bàn giao @nghivanbi nhe!

**Comment by chauthanhtra** [comment]
Kiểm tra lỗi này giúp em nha anh @nghivanbi . Pk nhắc hỏi mấy lần rồi

**Comment by nghivanbi** [comment]
@vinh-dh get mới này thử lại nhé.
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/91751241/a1a95e9e-5bf7-42ae-bec6-8d00722c7a60)

**Comment by vinh-dh** [comment]
@nghivanbi: DLL chỉ hỗ trợ sổ KB. Lỗi in toa ở issues này vẫn chưa hết.

![image](https://github.com/dh-hos/dhg.hospitalreports/assets/112069710/4ba19f9f-a4cc-4c23-8f43-6bbb3b60d663)

**Comment by nghivanbi** [comment]
Cập nhật thêm cái này nhé:
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/91751241/ddb7aa32-1857-4e68-8255-c2aa17cefbfe)

**Comment by vinh-dh** [comment]
Thử lại nhé @chauthanhtra 
File: [SetupHospitalReport20231010.zip](https://gofile.me/78TQg/X3VarMvX8)

**Comment by chauthanhtra** [comment]
Vẫn còn lỗi nha anh @vinh-dh 

![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/97272332/f031d77c-ffa8-40e3-8b33-ec690a8e647c)

**Comment by vinh-dh** [comment]
@nghivanbi
