### ISSUE TITLE
Lỗi - Báo cáo 25TH BANT không có tiền thuốc - cột Tổng cộng lệch so với các cột chi tiết cộng lại

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#76]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **09/08/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_hongngu_3360_xm2`

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**ThangKT**_: `07` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Báo cáo 25TH BANT không có tiền thuốc - cột Tổng cộng lệch so với các cột chi tiết cộng lại.

```
Mẫu 25TH
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/9e1b85a3-c4fa-457c-beea-a5d7556fd697)
Mẫu 25CT
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/124ea121-67c6-4046-9724-5b5760322160)

**Comment by vinh-dh** [comment]
Để a kiểm tra.

**Comment by vinh-dh** [comment]
- [SetupHospitalReport20230817](https://gofile.me/78TQg/TynDSBmgq)

**Comment by le-an-87** [comment]
đã fix!
