### ISSUE TITLE
Lỗi - Mẫu 3360 cổng update 27/08/2019 tổng tiền không khớp với tổng các cột chi phí cộng lại

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#78]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **09/08/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_hongngu_3360_2023010230`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/YOBImjkEt)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022015138` - _**MaKB**_: `2306013011` - _**MaBA**_: `2023010230` _**NgayKCB**_: `04/07/2023` - _**ThangKT**_: `07` - _**NamKT**_: `2023`
###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Mẫu excel CV 3360 - Cổng update 27/08/2019 xuất ra file Excel cột tổng cộng lệch tiền so với tổng các cột chi tiết cộng lại. Xuất file tại Form BC Xuất dữ liệu 4210/QĐ-BYT

```
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/45bfe4b3-403b-4b97-bf97-637c547dd563)

**Comment by vinh-dh** [comment]
- [SetupHospitalReport20230811](https://gofile.me/78TQg/aHoSbCFE9)

**Comment by le-an-87** [comment]
đã fix!
