### ISSUE TITLE
Lỗi - Lệch báo cáo giữa mẫu 79a (theo4210); XML và 25a-TH (theo4210) 

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitalreports#82]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Đức**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **18/09/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92092`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Quân Dân Y Cần Thơ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_qdy_report`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/66ameHUka

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > - _**ThangKT**_: `08` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Cột BN trả: 
    +  mẫu 79a (theo4210) và XML:  3.927.353,80đ
    + 25a-TH (theo4210):           3.989.528,00đ
                      Lệch:           62.174,20đ                    
```
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/98437757/e84ee254-45ea-4e5e-8213-b82fc732af4e)

![image](https://github.com/dh-hos/dhg.hospitalreports/assets/98437757/63ec1b78-d69d-4d8a-9a6d-29d5380599e5)

![image](https://github.com/dh-hos/dhg.hospitalreports/assets/98437757/e137a728-9c8c-44a1-b5b8-a583fde4cfcd)

**Comment by vinh-dh** [comment]
- [SetupHospitalReport20230920](https://gofile.me/78TQg/aTHHNRQND)
