### ISSUE TITLE
Lỗi - Mẫu 19,20,21 theo 3762 không xem được trang in, luôn hiện thông báo thiết kế trang in tài khoản thường

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalreports#84]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **1/10/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92092`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV QDY CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_phusanct_082023_26ath`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/YyB2Lq7SY)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `28/8/2023` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `08` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Mẫu in tự thiết kế 19, 20, 21 theo CV 3762 khi bấm in sẽ hiện thông báo Có muốn thiết kế lại trang in không dù đăng nhập bằng tài khoản thường (không phải tài khoản Admin ). bấm bỏ qua thì sẽ in trực tiếp ra giấy mà không hiện trang in cho người dùng xem trước.

=> BV muốn chỉnh lại: chỉ tài khoản Admin mới hiện thông báo cho thiết kế lại trang in và cho xem trước trang in trước khi in

Data test của BV Phụ sản, tài khoản đăng nhập: htbchi

![image](https://github.com/dh-hos/dhg.hospitalreports/assets/97272332/43a66f45-cb99-4c55-8eb9-88bfded0cebe)

**Comment by vinh-dh** [comment]
Đây không phải lỗi, đây là làm theo yêu cầu: [Yêu cầu - PK Đồng Tâm : yêu cầu bổ sung, thay đổi thông tin trên các mẫu sổ, báo cáo](https://github.com/dh-hos/To_Lap_Trinh/issues/73)

**Comment by ongtrieuhau** [comment]
Đây là lỗi code, lúc tạo trang in hông truyền tài khoản đăng nhập mà truyền bằng tài khoản admin nên mới hỏi lại thiết kế trang in. Anh @vinh-dh fix lại chỗ này giúp nhé a

**Comment by vinh-dh** [comment]
Đây là tài liệu hướng dẫn của @nghivanbi:
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/112069710/e631b09d-1322-4964-bb77-585b18660f67)

Còn đây là code đang áp dụng:
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/112069710/80fd5236-3d48-4a52-91e1-91f3a0b0afef)

Nếu có hướng dẫn mới hoặc thay đổi, đề nghị @nghivanbi cập nhật lại tài liệu nhe!

**Comment by ongtrieuhau** [comment]
Tài liệu vậy quá đúng rồi, vấn đề  anh đang truyền vào tài khoản admin thì nó mới có quyền edit, cái này anh truyền theo tài khoản đăng nhập của module là được rồi.

**Comment by vinh-dh** [comment]
File: [SetupHospitalReport20231006.zip](https://gofile.me/78TQg/X3VarMvX8)

**Comment by chauthanhtra** [comment]
Reports mới đã khắc phục được không cho tài khoản bình thường vào thiết kế 
Còn các lỗi sau:
- Mẫu 79, 20, 21 vẫn không cho xem bản in trước khi in. bấm nút in là nó in ra giấy luôn
- Mẫu 19 cho xem bản in trước khi in nhưng không cho thiết kế lại mẫu

**Comment by vinh-dh** [comment]
- Nhắc lại (xem chi tiết yêu cầu):
> Đây không phải lỗi, đây là làm theo yêu cầu: [Yêu cầu - PK Đồng Tâm : yêu cầu bổ sung, thay đổi thông tin trên các mẫu sổ, báo cáo](https://github.com/dh-hos/To_Lap_Trinh/issues/73)

- Trường hợp thao tác in ra giấy @nghivanbi kiểm tra và trả lời nhé!

**Comment by nghivanbi** [comment]
Thực hiện cho view nhé @vinh-dh 
Hàm tham khảo: XtraRPT.Xtra.PrintPreviewWithDefault

**Comment by vinh-dh** [comment]
> Thực hiện cho view nhé @vinh-dh Hàm tham khảo: XtraRPT.Xtra.PrintPreviewWithDefault

@nghivanbi: Cập nhật, bổ sung mô tả tài liệu đi. Căn cứ tài liệu mà làm.
