### ISSUE TITLE
Lỗi - Chức năng xuất Excel 917 mẫu 20 theo 4210 (form xuất XML QĐ 4210 - BV Lấp Vò)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#85]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **01/11/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_lapvo_full_01112023`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/ezKsapoZy)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**MaHH**_: `CA158` & _**MaHH**_: `CA164` - _**SoĐK**_: `VD-27518-17` - _**ThangKT**_: `10` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
File excel 917 mẫu 20 tổng hợp theo 4210 xuất từ Form XML dữ liệu QĐ 4210 tính sai số lượng đối với mã hàng hóa CA158 và CA164.


```
Excel 917 tính sai số lượng
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/a99479d7-0464-4d70-adeb-0340fbe5468c)

Thông tin thuốc
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/9d5acbdb-3a65-4aa9-a8a0-d100c20e4929)

**Comment by vinh-dh** [comment]
- File: [SetupHospitalReport20231103.zip](https://gofile.me/78TQg/9ZlS3PeMl)

**Comment by le-an-87** [comment]
Đã fix!
