### ISSUE TITLE
Lỗi - BC Bảng kê tổng hợp theo dịch vụ (BV Tim Mạch CT)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#86]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **02/11/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92001`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tim mạch TPCT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_timmach_ct_bcvp`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/dUWH51Jn0)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**ThangKT**_: `10` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Xuất báo cáo Bảng kê tổng hợp theo dịch vụ tháng 10/2023 phần mềm báo lỗi.

**BV đang cần xuất báo cáo tháng gấp.

```
Xuất cả tháng hoặc từ ngày 02/10 đến 16/10 đều lỗi giống nhau
![image](https://github.com/dh-hos/dhg.hospitalfees/assets/96155021/9ebbbb2f-8c21-4240-adbe-991f79f1cfe9)

**Comment by vinh-dh** [comment]
@ongtrieuhau kiểm tra giúp anh lỗi này. 

Reports đang sử dụng form:
`HosFees.Classes.ShowForm.TongHopDV(ClsInfoReports.strUserName, ClsInfoReports.strNamKT, ClsInfoReports.strThangKT, ClsInfoReports.ngaylamviec, OTH.Entity.Enum.Hos.v_LoaiKCB.TatCa, OTH.Entity.Enum.HosFees.Reports.TongHopDV.v_LoaiTongHop.TongHopDV, this);`

Phiên bản các thư viện:
- HosFees.dll: 3.23.927.6
- HosFees.BusinessLogic.dll: 3.23.412.3
- HosFees.BusinessLogicV2.dll: 3.23.412.1
- HosFees.DataAccess.dll: 3.23.915.1
- HosFees.DataAccessV2.dll: 3.23.915.4
- OTH.Common.dll: 1.23.928.12
- OTH.Entity.dll: 1.23.927.2
- OTH.Entity.v.1.0.dll: 1.23.811.1
