### ISSUE TITLE
Lỗi - Sổ khám bệnh bấm Xem báo lỗi

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitalreports#87]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Đức**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **07/11/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `mabvbh`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Trạm Thới Xuân**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_tramthoixuan_sokhambenh`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/iIWr5Jl9Q

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Xem Sổ khám bệnh báo lỗi

```
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/98437757/df10789f-7282-46ea-8104-7492173e0a7e)

**Comment by vinh-dh** [comment]
Cập nhật dll mới hay sao @nghivanbi ?

**Comment by nghivanbi** [comment]
Cập nhật lại DLL dùm nhé @vinh-dh, thank!

**Comment by vinh-dh** [comment]
HosReg.Code.dll phải không?

![image](https://github.com/dh-hos/dhg.hospitalreports/assets/112069710/c7fdfb36-5a7c-4494-a19e-c963ca30d8b9)

**Comment by nghivanbi** [comment]
đúng rồi gét mới thôi hà

**Comment by vinh-dh** [comment]
@minhduc2it kiểm tra lại data!
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/112069710/322d0bf9-bd50-43d2-b4ff-819c9b995764)

**Comment by minhduc2it** [comment]
@vinh-dh e restore data lại rồi anh

**Comment by vinh-dh** [comment]
- File: [SetupHospitalReport20231107.zip](https://gofile.me/78TQg/9ZlS3PeMl)

**Comment by minhduc2it** [comment]
đã test ok
