### ISSUE TITLE
Lỗi - Ghép tên cls PT sử dụng phương pháp vô cảm dư khoảng trắng (BV Trà Cú)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#89]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **15/11/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_tracu_ghepten_gt`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/tgYVBJfak)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023035643` - _**MaKB**_: `2311005690` - _**MaBA**_: `2023016303` _**NgayKCB**_: `13/11/2023` - _**MaPhong**_: `11.3` - _**MaDV**_: `KN` - _**ThangKT**_: `11` - _**NamKT**_: `2023`- _**MaCLS**_: `PH118`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Reports khi ghép tên đối với cls sử dụng phương pháp vô cảm không đúng theo mô tả và cổng văn CV1731-BHXH-GĐĐT

* Hiện tại khi ghép tên Reports ghép dư khoảng trắng.

```
mô tả [XML4210/20230415-Hau-CV1731-BHXH-GĐĐT-Thanh-toan-phau-thuat-vo-cam-gay-te.md](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML4210/20230415-Hau-CV1731-BHXH-G%C4%90%C4%90T-Thanh-toan-phau-thuat-vo-cam-gay-te.md)

không đồng nhất tên giữa Reports và admin
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/ef47f160-4091-4e9a-af31-5625cac3b65a)
Công văn
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/7981c29d-4a91-4ce3-86a6-41e5fc52d4fc)

**Comment by vinh-dh** [comment]
- File: [SetupHospitalReport20231117.zip](https://gofile.me/78TQg/9ZlS3PeMl)

**Comment by le-an-87** [comment]
Chổ form XML 4210 thì được rồi nhe anh @vinh-dh .
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/a6666655-5b7a-49a1-a70f-a3faaed733dc)

còn mẫu 21 thường chưa được anh ơi - anh cập nhật thêm chổ đó giùm em.
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/f2792f65-0c86-4d31-b000-63200859df49)

**Comment by vinh-dh** [comment]
- File: [SetupHospitalReport20231122.zip](https://gofile.me/78TQg/9ZlS3PeMl)

**Comment by le-an-87** [comment]
Đã fix!
