### ISSUE TITLE
Lỗi - xml2 có số lượng thuốc, thành tiền =0

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#9]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **30/9/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_quan12_reports_sl0`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2018110117` - _**MaKB**_: `2209027272` -_**NgayKCB**_: `26/9/2022` - _**MaPhong**_: `A1.05` - _**MaDV**_: `10` - _**ThangKT**_: `09` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `01` 
###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bệnh nhân in bảng kê chọn không lấy thuốc và in bảng kê để thanh toán cls
-> XML 2 Reports vẫn load thuốc của bệnh nhân đó -> soluong = 0, thanh tiền = 0
XML này gửi cổng bị lỗi

```
xml2 report
![image](https://user-images.githubusercontent.com/96155021/193237810-496836f9-538e-4ce1-a47c-2e3b199aaeea.png)

**Comment by vinh-dh** [comment]
Để a kiểm tra Reports

**Comment by vinh-dh** [comment]
[Reports 04/10/2022](https://www.fshare.vn/file/TGFK9CP7KYU5)

**Comment by le-an-87** [comment]
![image](https://user-images.githubusercontent.com/96155021/193959019-a6106742-007d-4f50-b5bf-3fbde524a403.png)
Fshare không tải được anh ơi

**Comment by vinh-dh** [comment]
Được bình thường
![image](https://user-images.githubusercontent.com/112069710/193963725-8ce3b422-62f5-4fe3-98ee-679fa24bdb1a.png)

**Comment by vinh-dh** [comment]
Click download, save file bình thường
![image](https://user-images.githubusercontent.com/112069710/193963965-df8190d5-1874-4fb8-bb96-018bd5fdf251.png)
