### ISSUE TITLE
Lỗi - Xuất sổ xét nghiệm quí - năm báo lỗi

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#91]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **28/11/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_sadec_gcs_27112023`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/aUxrtdChO)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**BaoCao**_: `Sổ xét nghiệm` _**ThangKt**_: `11` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Báo cáo sổ xét nghiệm khi lấy báo cáo quí, 6 tháng, 9 tháng và năm phát sinh lỗi.

* Lỗi ở cả 2 module Labor và Reports.

```
Labor
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/a99333a0-cb88-4f12-a0a9-3519c3fb184b)
Report
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/805a1f13-a314-4793-a3b7-a1c97e782c93)

**Comment by vinh-dh** [comment]
- File: [SetupHospitalReport20231201.zip](https://gofile.me/78TQg/9ZlS3PeMl)
- File: [HospitalLaboratorySetup20231201.zip](https://gofile.me/78TQg/B0ya25kSe)

**Comment by le-an-87** [comment]
Đã fix!
