### ISSUE TITLE
Lỗi - 

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/dhg.hospitalreports#93]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **07/12/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92004`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV ĐKTP CẦN THƠ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `ten_csdl`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Chạy report kết nối máy phụ đồng bộ phát sinh lỗi như hình:

```
![z4950572536431_07a44d4745fbc8d5197a53bf6183c97f](https://github.com/dh-hos/dhg.hospitalreports/assets/91751241/6f41dec6-8919-45d4-ae2f-6f0230c77003)

[ErrorMessage.log](https://github.com/dh-hos/dhg.hospitalreports/files/13594289/ErrorMessage.log)

**Comment by vinh-dh** [comment]
Lỗi này không phải lỗi truy vấn, cũng như không phải lỗi phần mềm nhé!

Nguyên nhân chính là do cơ chế hoạt động của máy chủ dự phòng bị ảnh hưởng. Xem chi tiết cảnh báo và hướng dẫn khi truy vấn dữ liệu trên máy chủ dự phòng của **PostgreSQL** tại đây: [Handling Query Conflicts](https://www.postgresql.org/docs/current/hot-standby.html#HOT-STANDBY-CONFLICT)
