### ISSUE TITLE
Lỗi - XML 4210 không tính sai chi phí nguồn khác (BV Thanh Bình)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#94]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **07/12/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87010`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Thanh Bình**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_thanhbinh_nguonkhac_07122023`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/Sgd9BeASi)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022027722` - _**MaKB**_: `2311006202` - _**MaBA**_: `N2023001561` _**NgayKCB**_: `16/11/2023` - _**MaPhong**_: `HIV` - _**MaDV**_: `10` - _**ThangKT**_: `11` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `08` - _**MaHH**_: `AC34` - _**SoHD**_: `K9.00035/202311` - _**NgayHD**_: `16/11/2023` - _**ThangKT**_: `11` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
BC XML 4210 không tách được chi phí bệnh nhân có sử thuốc thanh toán nguồn khác

* Mẫu 79 4210 thì tính được.

```
Mẫu 79 có chi phí nguồn khác
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/17081695-ae80-4125-b3f7-c873e51c534c)

XML 4210 không có chi phí nguồn khác
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/8e6d4abb-de25-4bca-870e-90d77b062bde)

**Comment by vinh-dh** [comment]
- File: [SetupHospitalReport20231215.zip](https://gofile.me/78TQg/9ZlS3PeMl)

**Comment by le-an-87** [comment]
Đã fix!
