### ISSUE TITLE
Lỗi - Báo cáo mẫu 21 tổng hợp (BV QDY ST)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalreports#95]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **12/12/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_qdy_st_gcv75_06122023`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/c913z0YTq)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**ThangKT**_: `12` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Xuất báo cáo mẫu 21 phần mềm báo lỗi.

```
một số hình ảnh lỗi khi xuất mẫu 21
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/be5b8e77-291a-45a4-aa37-fc4e0b04f69a)
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/a01e7a26-25a3-4a77-96f9-be409821f158)
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/96155021/6b968ce6-4c19-4f2a-91fb-8d8bfbf9a039)

**Comment by le-an-87** [comment]
Lỗi này nhiều chổ đang bị lỗi không xuất được mẫu 21. anh tranh thủ coi giùm em nhe anh!

**Comment by nghivanbi** [comment]
@vinh-dh tranh thủ coi xử lý lỗi này nhé

**Comment by vinh-dh** [comment]
- File: [SetupHospitalReport20231219.zip](https://gofile.me/78TQg/9ZlS3PeMl)

**Comment by le-an-87** [comment]
Đã fix!
