### ISSUE TITLE
Lỗi - Xét nghiệm đòm có trả kết quả nhưng không hiển thị lên XML bảng 3 cột ngay_ketqua

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalreports#96]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **06/12/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Trung tâm y tế huyện Thạnh Trị**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbthanhtri_xn`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2019016164` - _**MaKB**_: `2310010503` - _**MaBA**_: `2023008297` _**NgayKCB**_: `01/11/2023` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `19` - _**ThangKT**_: `11` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `AF03` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

![image](https://github.com/dh-hos/dhg.hospitallaboratory/assets/97272364/f9756dc6-aad5-4c2a-acdb-553820cdf537)
Phiếu kết quả
![image](https://github.com/dh-hos/dhg.hospitallaboratory/assets/97272364/fbe986e9-8115-4fda-8a70-fc58c104498c)

XML3 trên Report không hiển thị được ngày kết quả
![image](https://github.com/dh-hos/dhg.hospitallaboratory/assets/97272364/b1394eb2-b853-4030-90e9-64b5c0f46384)

**Comment by vinh-dh** [comment]
Cập nhật Labo luôn nhé @hvtuan1987.
- File: [HospitalLaboratorySetup20231213.zip](https://gofile.me/78TQg/B0ya25kSe)
- File: [SetupHospitalReport20231213.zip](https://gofile.me/78TQg/9ZlS3PeMl)

**Comment by hvtuan1987** [comment]
ok anh !

**Comment by hvtuan1987** [comment]
ok rồi á anh !
