### ISSUE TITLE
Lỗi - TEN_BENH XML1 không lấy được tên bệnh YHCT

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalreports#98]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **18/12/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `74206`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PK Medic Miền Đông**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_medic_bant_xml_tenbenhyhct_18122023`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/8rrtIQLG6)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023029295` - _**MaKB**_: `2312006319` - _**MaBA**_: `N2023017611` _**NgayKCB**_: `16/12/2023` - _**MaPhong**_: `11` - _**MaDV**_: `10` - _**ThangKT**_: `12` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

XML1 cột TEN_BENH không lấy được tên bệnh YHCT

[Bi - Mo ta thuoc ho tro benh nhan YHCT_20211201.2.pdf](https://github.com/dh-hos/dhg.hospitalreports/files/13699096/Bi.-.Mo.ta.thuoc.ho.tro.benh.nhan.YHCT_20211201.2.pdf)

Theo mô tả thì tên bệnh lấy dữ liệu từ bnnoitru.kqchandoanxml nhưng Reports không lấy đúng 

![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/97272332/1d03a8e8-327c-424b-805a-1ff340a9e9fe)
![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/97272332/c64c9701-027a-4f1d-a4f6-8a5d6e7f704a)
![ảnh](https://github.com/dh-hos/dhg.hospitalreports/assets/97272332/845cc082-d773-4849-a67e-cb1d17608dd4)

**Comment by vinh-dh** [comment]
- File: [SetupHospitalReport20231222.zip](https://gofile.me/78TQg/9ZlS3PeMl)
