### ISSUE TITLE
Lỗi - Sổ chẩn đoán hình ảnh check chọn Loại trừ CLS BHYT không thanh

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitalreports#99]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Đức**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **20/12/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77025`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PK Đông Tây**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_dongtay_sochandoan`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/cgaTxQXJe

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   >  _**NgayKCB**_: `20/12/2023` - _**MaDV**_: `MaDV` - _**ThangKT**_: `12` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Sổ chẩn đoán hình ảnh khi xem dữ liệu chọn Đối tượng: Tất cả và check chọn Loại trừ CLS BHYT không thanh lên sổ BHYT/TE
thì dữ liệu load luôn cả BN thu phí (CLS BHYT không thanh)

```
![image](https://github.com/dh-hos/dhg.hospitalreports/assets/98437757/755ea7d1-640d-474a-a02c-df50b5e7bdcf)

**Comment by vinh-dh** [comment]
Restore lại data nhé @minhduc2it

**Comment by vinh-dh** [comment]
- File: [SetupHospitalReport20240105.zip](https://gofile.me/78TQg/9ZlS3PeMl)

**Comment by minhduc2it** [comment]
đã test
